// packages/svelte/src/lib/components/accordion/AccordionField.svelte
<script lang="ts">
  import {
    buildAccordionFieldA11yIds,
    resolveAccordionFieldA11y,
    toAccordionFieldHtmlAttributes,
  } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import Text from "../text/Text.svelte";
  import Accordion from "./Accordion.svelte";
  import type { AccordionFieldItem, AccordionFieldProps } from "./types.js";

  let {
    id: userProvidedId,
    label,
    description,
    error,
    items,
    openItems: controlledOpen,
    defaultOpenItems,
    onopenitemschange,
    multiple = true,
    ariaDescribedBy,
    disabled,
    class: className,
  }: AccordionFieldProps = $props();

  const uniqueId = $props.id();
  const fieldId = $derived(userProvidedId ?? `mw-accordion-field-${uniqueId}`);

  function hasTextContent(text: string | undefined): boolean {
    return text !== undefined && text.trim().length > 0;
  }

  const hasDescription = $derived(hasTextContent(description));
  const hasError = $derived(hasTextContent(error));

  const a11yIds = $derived(
    buildAccordionFieldA11yIds({ id: fieldId, hasDescription, hasError, externalDescribedBy: ariaDescribedBy })
  );

  function getInitialOpenItems(): string[] {
    return defaultOpenItems ?? [];
  }

  let internalOpen = $state<string[]>(getInitialOpenItems());
  const activeOpen = $derived(controlledOpen ?? internalOpen);

  function toggleItem(value: string): void {
    let next: string[];
    if (activeOpen.includes(value)) {
      next = activeOpen.filter((v) => v !== value);
    } else {
      next = multiple ? [...activeOpen, value] : [value];
    }
    if (controlledOpen === undefined) {
      internalOpen = next;
    }
    onopenitemschange?.(next);
  }

  const wrapperClass = $derived(
    mergeClass(
      "mw-accordion-field",
      disabled && "mw-accordion-field--disabled",
      hasError && "mw-accordion-field--invalid",
      className
    )
  );
</script>

<!-- svelte-ignore a11y_role_supports_aria_props -->
<!-- a11y-allow: a div needs an explicit group role; React and Vue render a fieldset, which is an implicit group -->
<div
  class={wrapperClass}
  role="group"
  {...toAccordionFieldHtmlAttributes(
    resolveAccordionFieldA11y({ labelId: a11yIds.labelId, describedBy: a11yIds.describedBy, invalid: hasError })
  )}
>
  <div class="mw-accordion-field__label" id={a11yIds.labelId}>
    <Text variant="label">{label}</Text>
  </div>

  {#if hasDescription && !hasError}
    <div class="mw-accordion-field__description" id={a11yIds.descriptionId}>
      <Text variant="caption">{description}</Text>
    </div>
  {/if}

  <div class="mw-accordion-field__items">
    {#each items as item}
      <Accordion
        id={`${fieldId}-${item.value}`}
        title={item.title}
        open={activeOpen.includes(item.value)}
        disabled={disabled || item.disabled || false}
        ontoggle={() => toggleItem(item.value)}
      >
        {item.content}
      </Accordion>
    {/each}
  </div>

  {#if hasError}
    <div class="mw-accordion-field__error" id={a11yIds.errorId} aria-live="polite">
      <Text variant="caption">{error}</Text>
    </div>
  {/if}
</div>

// packages/react/src/components/accordion/accordion-field.tsx
/**
 * AccordionField (Molecule) — Recommended
 *
 * An accessible accordion group with field semantics: group label, optional
 * description, optional error, and coordinated open-state management.
 *
 * Composes `Accordion` atoms into a `role="group"` container with:
 * - a visible label wired via `aria-labelledby`
 * - optional `description` and `error` regions
 * - automatic `aria-describedby` wiring (description + error + external IDs)
 * - automatic `aria-invalid` when `error` is present
 * - controlled (`openItems` + `onOpenItemsChange`) or uncontrolled (`defaultOpenItems`) state
 * - single-open (`multiple=false`, default) or multi-open (`multiple=true`) behaviour
 *
 * Use `AccordionField` for most accordion groups. Use `Accordion` directly only
 * when you need a standalone collapsible panel outside of group semantics.
 *
 * @example Basic (uncontrolled, single-open)
 * ```tsx
 * <AccordionField
 *   label="FAQ"
 *   items={[
 *     { value: "q1", title: "What is Marwes?", content: <p>A design system.</p> },
 *     { value: "q2", title: "Is it free?", content: <p>Yes.</p> },
 *   ]}
 *   defaultOpenItems={["q1"]}
 * />
 * ```
 *
 * @example Multi-open, controlled
 * ```tsx
 * const [open, setOpen] = React.useState<string[]>([]);
 *
 * <AccordionField
 *   label="Settings"
 *   items={settingsItems}
 *   openItems={open}
 *   onOpenItemsChange={setOpen}
 *   multiple
 * />
 * ```
 */

import {
  buildAccordionFieldA11yIds,
  resolveAccordionFieldA11y,
  toAccordionFieldHtmlAttributes,
} from "@marwes-ui/core"
import * as React from "react"
import { toReactAttributes } from "../../internal/react-attributes"
import { Text } from "../text"
import { Accordion } from "./accordion"

export interface AccordionFieldItem {
  value: string
  title: React.ReactNode
  content?: React.ReactNode
  /** @deprecated Use `content` instead for cross-framework parity. */
  children?: React.ReactNode
  disabled?: boolean
}

export interface AccordionFieldProps {
  /** Visible label for the accordion group. */
  label: React.ReactNode

  /** Optional description text below the label. */
  description?: React.ReactNode

  /** Error message. When present, sets aria-invalid on the group. */
  error?: React.ReactNode

  /** Accordion items to render. */
  items: AccordionFieldItem[]

  /** Allow multiple items open simultaneously. Defaults to `true`. */
  multiple?: boolean

  /** Controlled: currently open item values. */
  openItems?: string[]

  /** Controlled: called with the new open-items array when state changes. */
  onOpenItemsChange?: (openItems: string[]) => void

  /** Uncontrolled: initially open item values. */
  defaultOpenItems?: string[]

  /** Disables all accordion items. */
  disabled?: boolean

  /** Explicit ID. If omitted, generated via useId(). */
  id?: string

  /** Additional aria-describedby IDs to merge with internal description/error IDs. */
  ariaDescribedBy?: string

  /** Data attributes for AI-friendly metadata (used by context variants). */
  dataAttributes?: Record<string, string>
}

function hasContent(value: React.ReactNode | undefined): boolean {
  if (value === undefined || value === null || value === false) return false
  if (typeof value === "string") return value.trim().length > 0
  return true
}

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function resolveAccordionItemContent(item: AccordionFieldItem): React.ReactNode {
  return item.content ?? item.children
}

export function AccordionField(props: AccordionFieldProps): React.ReactElement {
  const reactId = React.useId()
  const id = props.id ?? `mw-accordion-field-${reactId}`
  const multipleAllowed = props.multiple ?? true

  const hasDescription = hasContent(props.description)
  const hasError = hasContent(props.error)
  const isInvalid = hasError || false

  const { labelId, descriptionId, errorId, describedBy } = buildAccordionFieldA11yIds({
    id,
    hasDescription,
    hasError,
    externalDescribedBy: props.ariaDescribedBy,
  })

  // Controlled vs uncontrolled state
  const isControlled = props.openItems !== undefined
  const [internalOpenItems, setInternalOpenItems] = React.useState<string[]>(
    props.defaultOpenItems ?? [],
  )
  const openItems = isControlled ? (props.openItems ?? []) : internalOpenItems

  const handleToggle = (itemValue: string): void => {
    const isCurrentlyOpen = openItems.includes(itemValue)
    let nextOpenItems: string[]

    if (isCurrentlyOpen) {
      nextOpenItems = openItems.filter((v) => v !== itemValue)
    } else if (multipleAllowed) {
      nextOpenItems = [...openItems, itemValue]
    } else {
      nextOpenItems = [itemValue]
    }

    if (!isControlled) {
      setInternalOpenItems(nextOpenItems)
    }
    props.onOpenItemsChange?.(nextOpenItems)
  }

  const wrapperClass = cx(
    "mw-accordion-field",
    props.disabled && "mw-accordion-field--disabled",
    isInvalid && "mw-accordion-field--invalid",
  )

  return (
    <fieldset
      className={wrapperClass}
      {...toReactAttributes(
        toAccordionFieldHtmlAttributes(
          resolveAccordionFieldA11y({ labelId, describedBy, invalid: isInvalid }),
        ),
      )}
      {...props.dataAttributes}
    >
      <legend className="mw-accordion-field__label" id={labelId}>
        <Text variant="label">{props.label}</Text>
      </legend>

      <div className="mw-accordion-field__items">
        {props.items.map((item) => {
          const isDisabled = props.disabled || item.disabled || false
          const isOpen = openItems.includes(item.value)

          return (
            <Accordion
              key={item.value}
              id={`${id}-item-${item.value}`}
              title={item.title}
              open={isOpen}
              disabled={isDisabled}
              onToggle={() => handleToggle(item.value)}
            >
              {resolveAccordionItemContent(item)}
            </Accordion>
          )
        })}
      </div>

      {hasDescription && (
        <div className="mw-accordion-field__description" id={descriptionId}>
          <Text variant="caption">{props.description}</Text>
        </div>
      )}

      {hasError && (
        <div className="mw-accordion-field__error" id={errorId} aria-live="polite">
          <Text variant="caption">{props.error}</Text>
        </div>
      )}
    </fieldset>
  )
}
