// packages/react/src/components/context-menu/context-menu.tsx
import { createContextMenuRecipe } from "@marwes-ui/core"
import type { ContextMenuActionItem, ContextMenuEntry, ContextMenuOptions } from "@marwes-ui/core"
import type * as React from "react"
import { Icon } from "../icon"

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

export interface ContextMenuProps
  extends Omit<React.HTMLAttributes<HTMLDivElement>, "children" | "onSelect">,
    ContextMenuOptions {
  items: readonly ContextMenuEntry[]
  onSelect?: (value: string, item: ContextMenuActionItem) => void
}

export function ContextMenu(props: ContextMenuProps): React.ReactElement {
  const { items, ariaLabel, dataAttributes, onSelect, className, ...restProps } = props
  const recipeOptions: ContextMenuOptions = { items }

  if (ariaLabel !== undefined) {
    recipeOptions.ariaLabel = ariaLabel
  }

  if (dataAttributes !== undefined) {
    recipeOptions.dataAttributes = dataAttributes
  }

  const kit = createContextMenuRecipe(recipeOptions)

  return (
    <div
      {...restProps}
      {...kit.dataAttributes}
      className={cx(kit.className, className)}
      role={kit.a11y.role}
      aria-label={kit.a11y.ariaLabel}
    >
      {kit.items.map((item) => {
        if (item.kind === "divider") {
          return (
            <div
              key={item.key}
              className={item.className}
              role={item.a11y.role}
              aria-orientation={item.a11y.ariaOrientation}
              {...item.dataAttributes}
            />
          )
        }

        return (
          <button
            key={item.key}
            type={item.a11y.type}
            role={item.a11y.role}
            disabled={item.a11y.disabled}
            aria-disabled={item.a11y.ariaDisabled}
            className={item.className}
            onClick={() => {
              if (item.item.disabled) return
              onSelect?.(item.value, item.item)
            }}
            {...item.dataAttributes}
          >
            {item.icon && (
              <span className="mw-context-menu__icon" aria-hidden="true">
                <Icon name={item.icon} decorative />
              </span>
            )}
            <span className="mw-context-menu__label">{item.label}</span>
          </button>
        )
      })}
    </div>
  )
}

// packages/svelte/src/lib/components/context-menu/ContextMenu.svelte
<script lang="ts">
  import { createContextMenuRecipe } from "@marwes-ui/core";
  import Icon from "../icon/Icon.svelte";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { ContextMenuProps } from "./types.js";

  let {
    items,
    ariaLabel,
    dataAttributes,
    onselect,
    class: className,
  }: ContextMenuProps = $props();

  const menuOptions = $derived.by(() => {
    const options = { items };
    if (ariaLabel !== undefined) Object.assign(options, { ariaLabel });
    if (dataAttributes !== undefined) Object.assign(options, { dataAttributes });
    return options;
  });
  const kit = $derived(createContextMenuRecipe(menuOptions));
  const mergedClass = $derived(mergeClass(kit.className, className));
</script>

<div class={mergedClass} role={kit.a11y.role} aria-label={kit.a11y.ariaLabel} {...kit.dataAttributes}>
  {#each kit.items as item (item.key)}
    {#if item.kind === "divider"}
      <div
        class={item.className}
        role={item.a11y.role}
        aria-orientation={item.a11y.ariaOrientation}
        {...item.dataAttributes}
      ></div>
    {:else}
      <button
        type={item.a11y.type}
        role={item.a11y.role}
        disabled={item.a11y.disabled}
        aria-disabled={item.a11y.ariaDisabled}
        class={item.className}
        onclick={() => {
          if (item.item.disabled) return;
          onselect?.(item.value, item.item);
        }}
        {...item.dataAttributes}
      >
        {#if item.icon}
          <span class="mw-context-menu__icon" aria-hidden="true">
            <Icon name={item.icon} decorative />
          </span>
        {/if}
        <span class="mw-context-menu__label">{item.label}</span>
      </button>
    {/if}
  {/each}
</div>
