// packages/svelte/src/lib/components/switch/Switch.svelte
<script lang="ts">
  import { createSwitchRecipe } from "@marwes-ui/core";
  import { cssVarsToStyle, mergeStyle } from "../../internal/css-vars.js";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { SwitchProps } from "./types.js";

  let {
    children,
    class: className,
    id,
    oncheckedchange,
    onclick,
    ariaDescribedBy,
    ariaLabel,
    ...coreProps
  }: SwitchProps = $props();

  const kit = $derived(createSwitchRecipe({
    ...coreProps,
    ...(ariaDescribedBy ? { ariaDescribedBy } : {}),
    ...(ariaLabel ? { ariaLabel } : {}),
  }));
  const mergedClass = $derived(mergeClass(kit.className, className));
  const mergedStyle = $derived(cssVarsToStyle(kit.vars));
  const isDisabled = $derived(kit.a11y.ariaDisabled === true);

  function handleClick(e: MouseEvent): void {
    onclick?.(e);
    if (isDisabled || e.defaultPrevented) return;
    oncheckedchange?.(!kit.a11y.ariaChecked);
  }
</script>

<button
  {id}
  type="button"
  role={kit.a11y.role}
  disabled={isDisabled}
  aria-checked={kit.a11y.ariaChecked}
  aria-disabled={kit.a11y.ariaDisabled}
  aria-label={kit.a11y.ariaLabel}
  aria-labelledby={kit.a11y.ariaLabelledby}
  aria-describedby={kit.a11y.ariaDescribedBy}
  class={mergedClass}
  style={mergedStyle}
  onclick={handleClick}
>
  <span class="mw-switch__track">
    <span class="mw-switch__thumb"></span>
  </span>
  {@render children?.()}
</button>

// packages/react/src/components/switch/switch.tsx
import { createSwitchRecipe } from "@marwes-ui/core"
import type { SwitchOptions } from "@marwes-ui/core"
import type * as React from "react"

export type SwitchProps = SwitchOptions & {
  /** Label text rendered next to the toggle */
  children?: React.ReactNode
  className?: string
  id?: string
  onCheckedChange?: (checked: boolean) => void
  onClick?: React.MouseEventHandler<HTMLButtonElement>
}

export function Switch(props: SwitchProps): React.ReactElement {
  const { children, className, id, onCheckedChange, onClick, ...coreProps } = props
  const kit = createSwitchRecipe(coreProps)
  const { a11y } = kit
  const isDisabled = a11y.ariaDisabled === true

  const handleClick: React.MouseEventHandler<HTMLButtonElement> = (event) => {
    onClick?.(event)

    if (isDisabled || event.defaultPrevented) {
      return
    }

    onCheckedChange?.(!a11y.ariaChecked)
  }

  return (
    <button
      id={id}
      type="button"
      role={a11y.role}
      disabled={isDisabled}
      aria-checked={a11y.ariaChecked}
      aria-disabled={a11y.ariaDisabled}
      aria-label={a11y.ariaLabel}
      aria-labelledby={a11y.ariaLabelledBy}
      aria-describedby={a11y.ariaDescribedBy}
      className={[kit.className, className].filter(Boolean).join(" ")}
      style={kit.vars}
      onClick={handleClick}
    >
      <span className="mw-switch__track">
        <span className="mw-switch__thumb" />
      </span>
      {children}
    </button>
  )
}
