// packages/svelte/src/lib/components/switch/SwitchField.svelte
<script lang="ts">
  import { buildSwitchFieldA11yIds } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import Text from "../text/Text.svelte";
  import Switch from "./Switch.svelte";
  import type { SwitchFieldProps, SwitchProps } from "./types.js";


  let {
    id: userProvidedId,
    label,
    description,
    error,
    switch: switchProps = {},
    ariaDescribedBy,
    class: className,
  }: SwitchFieldProps = $props();

  const uniqueId = $props.id();
  const fieldId = $derived(userProvidedId ?? `mw-switch-${uniqueId}`);

  function hasTextContent(text: string | undefined): boolean {
    return text !== undefined && text.trim().length > 0;
  }

  const hasDescription = $derived(hasTextContent(description));
  const hasError = $derived(hasTextContent(error));
  const disabled = $derived(switchProps.disabled || false);

  const a11yIds = $derived(
    buildSwitchFieldA11yIds({
      id: fieldId,
      hasDescription,
      hasError,
      externalDescribedBy: ariaDescribedBy,
    })
  );

  const wrapperClass = $derived(
    mergeClass(
      "mw-switch-field",
      disabled && "mw-switch-field--disabled",
      hasError && "mw-switch-field--invalid",
      className
    )
  );
</script>

<div class={wrapperClass}>
  <div class="mw-switch-field__row">
    <Switch
      {...switchProps}
      id={fieldId}
      invalid={hasError}
      ariaDescribedBy={a11yIds.describedBy}
      ariaLabelledBy={a11yIds.labelId}
    />
    <label class="mw-switch-field__label" id={a11yIds.labelId} for={fieldId}>
      <Text variant="label">{label}</Text>
    </label>
  </div>

  {#if hasDescription}
    <div class="mw-switch-field__description" id={a11yIds.descriptionId}>
      <Text variant="caption">{description}</Text>
    </div>
  {/if}

  {#if hasError}
    <div class="mw-switch-field__error" id={a11yIds.errorId} aria-live="polite">
      <Text variant="caption">{error}</Text>
    </div>
  {/if}
</div>

// packages/react/src/components/switch/switch-field.tsx
import { buildSwitchFieldA11yIds } from "@marwes-ui/core"
import * as React from "react"
import { Text } from "../text"
import { Switch } from "./switch"
import type { SwitchProps } from "./switch"

export type SwitchFieldProps = {
  id?: string
  label: React.ReactNode
  description?: React.ReactNode
  error?: React.ReactNode
  switch: SwitchProps
  ariaDescribedBy?: string
  dataAttributes?: Record<string, string>
}

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function hasContent(value: React.ReactNode | undefined): boolean {
  if (value === undefined || value === null || value === false) {
    return false
  }

  if (typeof value === "string") {
    return value.trim().length > 0
  }

  return true
}

export function SwitchField(props: SwitchFieldProps): React.ReactElement {
  const reactId = React.useId()
  const id = props.id ?? `mw-switch-${reactId}`
  const hasDescription = hasContent(props.description)
  const hasError = hasContent(props.error)
  const { labelId, descriptionId, errorId, describedBy } = buildSwitchFieldA11yIds({
    id,
    hasDescription,
    hasError,
    externalDescribedBy: props.ariaDescribedBy,
  })

  const disabled = props.switch.disabled || false
  const invalid = hasError
  const wrapperClass = cx(
    "mw-switch-field",
    disabled && "mw-switch-field--disabled",
    invalid && "mw-switch-field--invalid",
  )
  const {
    ariaLabel: _ignoredAriaLabel,
    ariaLabelledby: _ignoredAriaLabelledby,
    ariaDescribedBy: _ignoredAriaDescribedBy,
    children: _ignoredChildren,
    ...switchProps
  } = props.switch

  return (
    <div className={wrapperClass} {...props.dataAttributes}>
      <div className="mw-switch-field__row">
        <Switch
          {...switchProps}
          id={id}
          ariaLabelledby={labelId}
          {...(describedBy ? { ariaDescribedBy: describedBy } : {})}
        />

        <span className="mw-switch-field__label" id={labelId}>
          <Text variant="label">{props.label}</Text>
        </span>
      </div>

      {hasDescription && (
        <div className="mw-switch-field__description" id={descriptionId}>
          <Text variant="caption">{props.description}</Text>
        </div>
      )}

      {hasError && (
        <div className="mw-switch-field__error" id={errorId} aria-live="polite">
          <Text variant="caption">{props.error}</Text>
        </div>
      )}
    </div>
  )
}
