// packages/svelte/src/lib/components/heading/H1.svelte
<!--
  H1 (Heading Level 1) — semantic top-level heading rendered as `<h1>`.

  @remarks
  Marwes officially styles H1-H3 only. For semantic H4-H6 (deep section
  nesting, accessibility outlines), render
  `<Text headingLevel={4} variant="..." />` — it produces the correct
  heading tag while letting the consumer pick the visual variant.
  Type your wrappers against `SemanticHeadingLevel` from `@marwes-ui/core`.
-->
<script lang="ts">
  import { headingRecipe } from "@marwes-ui/core";
  import { cssVarsToStyle, mergeStyle } from "../../internal/css-vars.js";
  import { mergeClass } from "../../internal/merge-class.js";
  import { useTheme } from "../../provider/use-theme.js";
  import type { H1Props } from "./types.js";

  let {
    children,
    class: className,
    style,
    ...opts
  }: H1Props = $props();

  const { theme } = useTheme();
  const kit = $derived(headingRecipe({ ...opts, level: 1 }, theme));
  const mergedClass = $derived(mergeClass(kit.className, className));
  const mergedStyle = $derived(mergeStyle(cssVarsToStyle(kit.vars), style));
</script>

<h1 id={kit.a11y.id} aria-label={kit.a11y.ariaLabel} class={mergedClass} style={mergedStyle}>
  {@render children?.()}
</h1>

// packages/react/src/components/heading/h1.tsx
/**
 * React adapter for Marwes H1 component.
 * - Renders semantic <h1> using the core heading recipe.
 * - Supports size override for visual/semantic mismatch.
 */

import { headingRecipe } from "@marwes-ui/core"
import type { HeadingOptions, HeadingSize } from "@marwes-ui/core"
import type { CssVars } from "@marwes-ui/core"
import type * as React from "react"
import { useTheme } from "../../provider/use-theme"

type StyleWithVars = React.CSSProperties & CssVars

export type H1Props = Omit<HeadingOptions, "level"> & {
  /**
   * Visual size override.
   * Allows using h1 semantics with different visual styling.
   * @default "h1"
   */
  size?: HeadingSize

  /**
   * Content of the heading.
   */
  children?: React.ReactNode

  /**
   * Additional CSS class names.
   */
  className?: string

  /**
   * Inline styles.
   */
  style?: React.CSSProperties
}

/**
 * H1 (Heading Level 1)
 *
 * Semantic top-level heading rendered as `<h1>`.
 * Supports visual size override for cases where semantic and visual hierarchy differ.
 *
 * @remarks
 * Marwes officially styles H1-H3 only. For semantic H4-H6 (deep section
 * nesting, accessibility outlines), render `<Text headingLevel={4..6}
 * variant="..." />` — it produces the correct heading tag while letting
 * the consumer pick the visual variant. Type your wrappers against
 * `SemanticHeadingLevel` from `@marwes-ui/core`.
 *
 * @example Basic usage
 * ```tsx
 * <H1>Page Title</H1>
 * ```
 *
 * @example With size override
 * ```tsx
 * <H1 size="h2">Visually smaller but semantically h1</H1>
 * ```
 *
 * @example With ID for anchor linking
 * ```tsx
 * <H1 id="introduction">Introduction</H1>
 * ```
 */
export function H1(props: H1Props): React.ReactElement {
  const { children, className: customClassName, style: customStyle, ...opts } = props
  const theme = useTheme()

  const kit = headingRecipe({ ...opts, level: 1 }, theme)

  const style = { ...(kit.vars as StyleWithVars), ...customStyle }
  const className = customClassName ? `${kit.className} ${customClassName}` : kit.className

  return (
    <h1 id={kit.a11y.id} aria-label={kit.a11y.ariaLabel} className={className} style={style}>
      {children}
    </h1>
  )
}
