// packages/react/src/components/toast/toast.tsx
import { createToastRecipe } from "@marwes-ui/core"
import type { ToastOptions } from "@marwes-ui/core"
import type * as React from "react"

export interface ToastProps extends ToastOptions {
  /** Main notification message */
  children: React.ReactNode
  /** Icon element shown on the left (e.g. an <Icon> component) */
  icon?: React.ReactNode
  /** Action element shown below the message (e.g. a <button> or <a>) */
  action?: React.ReactNode
  /** When provided, renders a dismiss (×) button and calls this on click */
  onDismiss?: () => void
  className?: string
  id?: string
}

export function Toast(props: ToastProps): React.ReactElement {
  const { children, icon, action, onDismiss, className, id, ...coreProps } = props
  const kit = createToastRecipe(coreProps)
  const { a11y } = kit

  return (
    <div
      id={id}
      className={[kit.className, className].filter(Boolean).join(" ")}
      role={a11y.role}
      aria-live={a11y.ariaLive}
      aria-atomic="true"
    >
      {icon && (
        <span className="mw-toast__icon" aria-hidden="true">
          {icon}
        </span>
      )}
      <div className="mw-toast__body">
        <span className="mw-toast__text">{children}</span>
        {action && <span className="mw-toast__action">{action}</span>}
      </div>
      {onDismiss && (
        <button
          type="button"
          className="mw-toast__dismiss"
          aria-label="Dismiss"
          onClick={onDismiss}
        />
      )}
    </div>
  )
}

// packages/svelte/src/lib/components/toast/Toast.svelte
<script lang="ts">
  import { createToastRecipe } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { ToastProps } from "./types.js";

  let {
    children,
    icon,
    action,
    ondismiss,
    class: className,
    id,
    dataAttributes,
    ...coreProps
  }: ToastProps = $props();

  const kit = $derived(createToastRecipe(coreProps));
  const mergedClass = $derived(mergeClass(kit.className, className));
</script>

<div
  {id}
  class={mergedClass}
  role={kit.a11y.role}
  aria-live={kit.a11y.ariaLive}
  aria-atomic="true"
  {...kit.dataAttributes}
  {...dataAttributes}
>
  {#if icon}
    <span class="mw-toast__icon" aria-hidden="true">
      {@render icon()}
    </span>
  {/if}
  <div class="mw-toast__body">
    <span class="mw-toast__text">
      {@render children?.()}
    </span>
    {#if action}
      <span class="mw-toast__action">
        {@render action()}
      </span>
    {/if}
  </div>
  {#if ondismiss}
    <button
      type="button"
      class="mw-toast__dismiss"
      aria-label="Dismiss"
      onclick={ondismiss}
    ></button>
  {/if}
</div>
