// packages/svelte/src/lib/components/drawer/Drawer.svelte
<script lang="ts">
  import { IconName, createDrawerRecipe } from "@marwes-ui/core";
  import type { DrawerOptions } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import Icon from "../icon/Icon.svelte";
  import type { DrawerProps } from "./types.js";

  let {
    id: userProvidedId,
    title,
    description,
    children,
    footer,
    onclose,
    class: className,
    panelClass,
    dataAttributes,
    size,
    placement,
    showFooter,
    dismissible,
    modal,
    showScrim,
    ariaLabel,
    ariaLabelledBy,
    ariaDescribedBy,
  }: DrawerProps = $props();

  const uniqueId = $props.id();
  const drawerId = $derived(userProvidedId ?? `mw-drawer-${uniqueId}`);
  const titleId = $derived(`${drawerId}-title`);
  const descriptionId = $derived(`${drawerId}-description`);

  const hasTitle = $derived(title !== undefined && title.trim().length > 0);
  const hasDescription = $derived(description !== undefined && description.trim().length > 0);
  const hasFooter = $derived((showFooter ?? true) && footer !== undefined);
  const isDismissible = $derived((dismissible ?? true) && onclose !== undefined);

  const drawerOptions = $derived.by((): DrawerOptions => {
    const opts: DrawerOptions = {
      showFooter: hasFooter,
      dismissible: isDismissible,
    };
    if (modal !== undefined) opts.modal = modal;
    if (showScrim !== undefined) opts.showScrim = showScrim;
    if (dataAttributes !== undefined) opts.dataAttributes = dataAttributes;
    if (size !== undefined) opts.size = size;
    if (placement !== undefined) opts.placement = placement;
    if (ariaLabel !== undefined) opts.ariaLabel = ariaLabel;
    if (ariaLabelledBy !== undefined) {
      opts.ariaLabelledBy = ariaLabelledBy;
    } else if (ariaLabel === undefined && hasTitle) {
      opts.ariaLabelledBy = titleId;
    }
    if (ariaDescribedBy !== undefined) {
      opts.ariaDescribedBy = ariaDescribedBy;
    } else if (hasDescription) {
      opts.ariaDescribedBy = descriptionId;
    }
    return opts;
  });

  const kit = $derived(createDrawerRecipe(drawerOptions));
  const mergedClass = $derived(mergeClass(kit.className, className));
  const mergedPanelClass = $derived(mergeClass(kit.panel.className, panelClass));

  function handleClose(): void {
    onclose?.();
  }
</script>

<div class={mergedClass} {...kit.dataAttributes}>
  {#if kit.showScrim}
    <div
      class={kit.scrim.className}
      aria-hidden="true"
      onclick={isDismissible ? handleClose : undefined}
      {...kit.scrim.dataAttributes}
    ></div>
  {/if}

  <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
  <aside
    id={drawerId}
    class={mergedPanelClass}
    role={kit.panel.a11y.role}
    aria-modal={kit.panel.a11y.ariaModal ? "true" : undefined}
    aria-label={kit.panel.a11y.ariaLabel}
    aria-labelledby={kit.panel.a11y.ariaLabelledBy}
    aria-describedby={kit.panel.a11y.ariaDescribedBy}
    tabindex={-1}
    {...kit.panel.dataAttributes}
  >
    {#if hasTitle || kit.showCloseButton}
      <header class="mw-drawer__header">
        {#if hasTitle}
          <div class="mw-drawer__heading-group">
            <h2 class="mw-drawer__title" id={titleId}>{title}</h2>
          </div>
        {:else}
          <span class="mw-drawer__spacer" aria-hidden="true"></span>
        {/if}

        {#if kit.showCloseButton && onclose}
          <button
            type="button"
            class="mw-drawer__close"
            aria-label="Close drawer"
            onclick={handleClose}
          >
            <Icon name={IconName.X} decorative />
          </button>
        {/if}
      </header>
      <div class="mw-drawer__header-divider" aria-hidden="true"></div>
    {/if}

    <div class="mw-drawer__content">
      {#if hasDescription}
        <p class="mw-drawer__description" id={descriptionId}>{description}</p>
      {/if}
      {@render children?.()}
    </div>

    {#if hasFooter}
      <div class="mw-drawer__footer-divider" aria-hidden="true"></div>
      <footer class="mw-drawer__footer">
        {@render footer?.({ close: handleClose })}
      </footer>
    {/if}
  </aside>
</div>

// packages/react/src/components/drawer/drawer.tsx
import { type DrawerOptions, IconName, createDrawerRecipe } from "@marwes-ui/core"
import * as React from "react"
import { Icon } from "../icon"

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function hasContent(value: React.ReactNode | undefined): boolean {
  if (value === undefined || value === null || value === false) {
    return false
  }

  if (typeof value === "string") {
    return value.trim().length > 0
  }

  return true
}

export interface DrawerProps extends DrawerOptions {
  id?: string
  title?: React.ReactNode
  description?: React.ReactNode
  footer?: React.ReactNode
  children?: React.ReactNode
  onClose?: () => void
  className?: string
  panelClassName?: string
  dataAttributes?: Record<string, string>
}

export function Drawer(props: DrawerProps): React.ReactElement {
  const reactId = React.useId()
  const id = props.id ?? `mw-drawer-${reactId}`
  const titleId = `${id}-title`
  const descriptionId = `${id}-description`
  const hasTitle = hasContent(props.title)
  const hasDescription = hasContent(props.description)
  const hasFooter = hasContent(props.footer) && (props.showFooter ?? true)
  const dismissible = (props.dismissible ?? true) && props.onClose !== undefined
  const drawerOptions: DrawerOptions = {
    showFooter: hasFooter,
    dismissible,
    ...(props.modal !== undefined ? { modal: props.modal } : {}),
    ...(props.showScrim !== undefined ? { showScrim: props.showScrim } : {}),
  }

  if (props.dataAttributes) {
    drawerOptions.dataAttributes = props.dataAttributes
  }

  if (props.size) {
    drawerOptions.size = props.size
  }

  if (props.placement) {
    drawerOptions.placement = props.placement
  }

  if (props.ariaLabel) {
    drawerOptions.ariaLabel = props.ariaLabel
  }

  if (props.ariaLabelledBy) {
    drawerOptions.ariaLabelledBy = props.ariaLabelledBy
  } else if (props.ariaLabel === undefined && hasTitle) {
    drawerOptions.ariaLabelledBy = titleId
  }

  if (props.ariaDescribedBy) {
    drawerOptions.ariaDescribedBy = props.ariaDescribedBy
  } else if (hasDescription) {
    drawerOptions.ariaDescribedBy = descriptionId
  }

  const kit = createDrawerRecipe(drawerOptions)

  return (
    <div className={cx(kit.className, props.className)} style={kit.vars} {...kit.dataAttributes}>
      {kit.showScrim && (
        <div
          className={kit.scrim.className}
          style={kit.scrim.vars}
          aria-hidden="true"
          onClick={dismissible ? props.onClose : undefined}
          {...kit.scrim.dataAttributes}
        />
      )}

      <aside
        id={id}
        className={cx(kit.panel.className, props.panelClassName)}
        style={kit.panel.vars}
        role={kit.panel.a11y.role}
        {...(kit.panel.a11y.ariaModal ? { "aria-modal": "true" } : {})}
        {...(kit.panel.a11y.ariaLabel ? { "aria-label": kit.panel.a11y.ariaLabel } : {})}
        {...(kit.panel.a11y.ariaLabelledBy
          ? { "aria-labelledby": kit.panel.a11y.ariaLabelledBy }
          : {})}
        {...(kit.panel.a11y.ariaDescribedBy
          ? { "aria-describedby": kit.panel.a11y.ariaDescribedBy }
          : {})}
        tabIndex={-1}
        {...kit.panel.dataAttributes}
      >
        {(hasTitle || kit.showCloseButton) && (
          <>
            <header className="mw-drawer__header">
              {hasTitle ? (
                <div className="mw-drawer__heading-group">
                  <h2 className="mw-drawer__title" id={titleId}>
                    {props.title}
                  </h2>
                </div>
              ) : (
                <span className="mw-drawer__spacer" aria-hidden="true" />
              )}

              {kit.showCloseButton && props.onClose && (
                <button
                  type="button"
                  className="mw-drawer__close"
                  aria-label="Close drawer"
                  onClick={props.onClose}
                >
                  <Icon name={IconName.X} decorative />
                </button>
              )}
            </header>
            <div className="mw-drawer__header-divider" aria-hidden="true" />
          </>
        )}

        <div className="mw-drawer__content">
          {hasDescription && (
            <p className="mw-drawer__description" id={descriptionId}>
              {props.description}
            </p>
          )}
          {props.children}
        </div>

        {hasFooter && (
          <>
            <div className="mw-drawer__footer-divider" aria-hidden="true" />
            <footer className="mw-drawer__footer">{props.footer}</footer>
          </>
        )}
      </aside>
    </div>
  )
}
