// packages/svelte/src/lib/components/skeleton/Skeleton.svelte
<script lang="ts">
  import { createSkeletonRecipe } from "@marwes-ui/core";
  import { cssVarsToStyle, mergeStyle } from "../../internal/css-vars.js";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { SkeletonProps } from "./types.js";

  let {
    class: className,
    style,
    ...options
  }: SkeletonProps = $props();

  const kit = $derived(createSkeletonRecipe(options));
  const mergedClass = $derived(mergeClass(kit.className, className));
  const mergedStyle = $derived(mergeStyle(cssVarsToStyle(kit.vars), style));
</script>

<span
  class={mergedClass}
  style={mergedStyle}
  id={kit.a11y.id}
  role={kit.a11y.role}
  aria-hidden={kit.a11y.ariaHidden ? "true" : undefined}
  aria-label={kit.a11y.ariaLabel}
  aria-live={kit.a11y.ariaLive}
  data-component={kit.dataAttributes["data-component"]}
  data-variant={kit.dataAttributes["data-variant"]}
  data-animation={kit.dataAttributes["data-animation"]}
></span>

// packages/react/src/components/skeleton/skeleton.tsx
import { type CssVars, type SkeletonOptions, createSkeletonRecipe } from "@marwes-ui/core"
import type * as React from "react"

type StyleWithVars = React.CSSProperties & CssVars

export interface SkeletonProps
  extends SkeletonOptions,
    Omit<React.HTMLAttributes<HTMLSpanElement>, "children"> {
  dataAttributes?: Record<string, string>
}

export function Skeleton(props: SkeletonProps): React.ReactElement {
  const {
    className,
    style,
    dataAttributes,
    variant,
    width,
    height,
    radius,
    animation,
    decorative,
    ariaLabel,
    id,
    ...nativeSpanProps
  } = props

  const resolvedAriaLabel =
    ariaLabel ??
    (typeof nativeSpanProps["aria-label"] === "string"
      ? (nativeSpanProps["aria-label"] as string)
      : undefined)

  const skeletonOptions: SkeletonOptions = {
    ...(variant !== undefined ? { variant } : {}),
    ...(width !== undefined ? { width } : {}),
    ...(height !== undefined ? { height } : {}),
    ...(radius !== undefined ? { radius } : {}),
    ...(animation !== undefined ? { animation } : {}),
    ...(decorative !== undefined ? { decorative } : {}),
    ...(resolvedAriaLabel !== undefined ? { ariaLabel: resolvedAriaLabel } : {}),
    ...(id !== undefined ? { id } : {}),
  }

  const renderKit = createSkeletonRecipe(skeletonOptions)
  const mergedClassName = [renderKit.className, className].filter(Boolean).join(" ")
  const mergedStyle = { ...(renderKit.vars as StyleWithVars), ...style }

  return (
    <span
      {...nativeSpanProps}
      {...renderKit.dataAttributes}
      {...dataAttributes}
      className={mergedClassName}
      style={mergedStyle}
      role={renderKit.a11y.role}
      id={renderKit.a11y.id}
      aria-hidden={renderKit.a11y.ariaHidden ? "true" : undefined}
      aria-label={renderKit.a11y.ariaLabel}
      aria-live={renderKit.a11y.ariaLive}
    />
  )
}
