// packages/svelte/src/lib/components/card/Card.svelte
<script lang="ts">
  import { createCardRecipe } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { CardProps } from "./types.js";

  let {
    title,
    children,
    class: className,
    id,
    dataAttributes,
  }: CardProps = $props();

  const kit = $derived(createCardRecipe(dataAttributes ? { dataAttributes } : {}));
  const mergedClass = $derived(mergeClass(kit.className, className));
</script>

<div {id} class={mergedClass} {...kit.dataAttributes}>
  {#if title}
    <div class="mw-card__header">
      <span class="mw-card__title">
        {#if typeof title === "string"}
          {title}
        {:else}
          {@render title()}
        {/if}
      </span>
    </div>
  {/if}
  <div class="mw-card__body">
    {@render children?.()}
  </div>
</div>

// packages/react/src/components/card/card.tsx
import { createCardRecipe } from "@marwes-ui/core"
import type * as React from "react"

export interface CardProps {
  /** Optional title rendered in a header area above the body */
  title?: React.ReactNode
  /** Card body content */
  children?: React.ReactNode
  className?: string
  id?: string
}

export function Card(props: CardProps): React.ReactElement {
  const { title, children, className, id } = props
  const kit = createCardRecipe()

  return (
    <div id={id} className={[kit.className, className].filter(Boolean).join(" ")}>
      {title && (
        <div className="mw-card__header">
          <span className="mw-card__title">{title}</span>
        </div>
      )}
      <div className="mw-card__body">{children}</div>
    </div>
  )
}
