// packages/react/src/components/date-picker/date-picker.tsx
import {
  type DatePickerDay,
  type DatePickerDevice,
  type DatePickerOptions,
  createDatePickerRecipe,
} from "@marwes-ui/core"
import type * as React from "react"

export interface DatePickerProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "children" | "onSelect">,
    Pick<
      DatePickerOptions,
      | "monthLabel"
      | "weekdayLabels"
      | "weeks"
      | "previousYearLabel"
      | "previousMonthLabel"
      | "nextMonthLabel"
      | "nextYearLabel"
      | "cancelLabel"
      | "applyLabel"
      | "calendarLabel"
      | "dataAttributes"
    > {
  device?: DatePickerDevice
  onPreviousYear?: () => void
  onPreviousMonth?: () => void
  onNextMonth?: () => void
  onNextYear?: () => void
  onDaySelect?: (day: DatePickerDay) => void
  onCancel?: () => void
  onApply?: () => void
}

export function DatePicker(props: DatePickerProps): React.ReactElement {
  const {
    className,
    monthLabel,
    weekdayLabels,
    weeks,
    device,
    previousYearLabel,
    previousMonthLabel,
    nextMonthLabel,
    nextYearLabel,
    cancelLabel,
    applyLabel,
    calendarLabel,
    dataAttributes,
    onPreviousYear,
    onPreviousMonth,
    onNextMonth,
    onNextYear,
    onDaySelect,
    onCancel,
    onApply,
    ...nativeProps
  } = props
  const kit = createDatePickerRecipe({
    ...(monthLabel !== undefined ? { monthLabel } : {}),
    ...(weekdayLabels !== undefined ? { weekdayLabels } : {}),
    ...(weeks !== undefined ? { weeks } : {}),
    ...(device !== undefined ? { device } : {}),
    ...(previousYearLabel !== undefined ? { previousYearLabel } : {}),
    ...(previousMonthLabel !== undefined ? { previousMonthLabel } : {}),
    ...(nextMonthLabel !== undefined ? { nextMonthLabel } : {}),
    ...(nextYearLabel !== undefined ? { nextYearLabel } : {}),
    ...(cancelLabel !== undefined ? { cancelLabel } : {}),
    ...(applyLabel !== undefined ? { applyLabel } : {}),
    ...(calendarLabel !== undefined ? { calendarLabel } : {}),
    ...(dataAttributes !== undefined ? { dataAttributes } : {}),
  })
  const mergedClassName = [kit.className, className].filter(Boolean).join(" ")

  return (
    <section
      {...nativeProps}
      {...kit.dataAttributes}
      className={mergedClassName}
      aria-label={kit.labels.calendar}
    >
      <header className={kit.slots.headerClassName}>
        <div className={kit.slots.navGroupClassName}>
          <button
            type="button"
            className={kit.slots.navButtonClassName}
            aria-label={kit.labels.previousYear}
            onClick={onPreviousYear}
          >
            «
          </button>
          <button
            type="button"
            className={kit.slots.navButtonClassName}
            aria-label={kit.labels.previousMonth}
            onClick={onPreviousMonth}
          >
            ‹
          </button>
        </div>
        <div className={kit.slots.monthLabelClassName}>{kit.monthLabel}</div>
        <div className={kit.slots.navGroupClassName}>
          <button
            type="button"
            className={kit.slots.navButtonClassName}
            aria-label={kit.labels.nextMonth}
            onClick={onNextMonth}
          >
            ›
          </button>
          <button
            type="button"
            className={kit.slots.navButtonClassName}
            aria-label={kit.labels.nextYear}
            onClick={onNextYear}
          >
            »
          </button>
        </div>
      </header>
      <table className={kit.slots.gridClassName} aria-label={kit.monthLabel}>
        <thead>
          <tr className="mw-date-picker__weekdays">
            {kit.weekdayLabels.map((weekday) => (
              <th key={weekday} className={kit.slots.weekdayClassName} scope="col">
                {weekday}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {kit.weeks.map((week, weekIndex) => (
            <tr
              key={week.map((day) => day.date ?? day.label).join("-")}
              className={kit.slots.weekClassName}
            >
              {week.map((day, dayIndex) => {
                const dayKit = kit.dayKits[weekIndex]?.[dayIndex]
                if (!dayKit) return null
                return (
                  <td
                    key={day.date ?? `${weekIndex}-${dayIndex}`}
                    className={kit.slots.cellClassName}
                  >
                    <button
                      type="button"
                      {...dayKit.dataAttributes}
                      className={dayKit.className}
                      aria-label={dayKit.ariaLabel}
                      aria-pressed={dayKit.selected ? "true" : undefined}
                      disabled={dayKit.disabled}
                      onClick={() => onDaySelect?.(day)}
                    >
                      {day.label}
                    </button>
                  </td>
                )
              })}
            </tr>
          ))}
        </tbody>
      </table>
      <footer className={kit.slots.footerClassName}>
        <button type="button" className={kit.slots.footerButtonClassName} onClick={onCancel}>
          {kit.labels.cancel}
        </button>
        {kit.labels.apply ? (
          <button
            type="button"
            className={`${kit.slots.footerButtonClassName} mw-date-picker__footer-button--primary`}
            onClick={onApply}
          >
            {kit.labels.apply}
          </button>
        ) : null}
      </footer>
    </section>
  )
}

// packages/svelte/src/lib/components/date-picker/DatePicker.svelte
<script lang="ts">
  import { createDatePickerRecipe } from "@marwes-ui/core";
  import type { DatePickerDay, DatePickerDevice, DatePickerOptions } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";

  interface DatePickerProps {
    monthLabel?: string;
    weekdayLabels?: string[];
    weeks?: DatePickerDay[][];
    device?: DatePickerDevice;
    previousYearLabel?: string;
    previousMonthLabel?: string;
    nextMonthLabel?: string;
    nextYearLabel?: string;
    cancelLabel?: string;
    applyLabel?: string;
    calendarLabel?: string;
    dataAttributes?: Record<string, string>;
    onpreviousyear?: () => void;
    onpreviousmonth?: () => void;
    onnextmonth?: () => void;
    onnextyear?: () => void;
    ondayselect?: (day: DatePickerDay) => void;
    oncancel?: () => void;
    onapply?: () => void;
    class?: string;
  }

  let {
    monthLabel,
    weekdayLabels,
    weeks,
    device,
    previousYearLabel,
    previousMonthLabel,
    nextMonthLabel,
    nextYearLabel,
    cancelLabel,
    applyLabel,
    calendarLabel,
    dataAttributes,
    onpreviousyear,
    onpreviousmonth,
    onnextmonth,
    onnextyear,
    ondayselect,
    oncancel,
    onapply,
    class: className,
  }: DatePickerProps = $props();

  const recipeOptions = $derived.by((): DatePickerOptions => {
    const opts: DatePickerOptions = {};
    if (monthLabel !== undefined) opts.monthLabel = monthLabel;
    if (weekdayLabels !== undefined) opts.weekdayLabels = weekdayLabels;
    if (weeks !== undefined) opts.weeks = weeks;
    if (device !== undefined) opts.device = device;
    if (previousYearLabel !== undefined) opts.previousYearLabel = previousYearLabel;
    if (previousMonthLabel !== undefined) opts.previousMonthLabel = previousMonthLabel;
    if (nextMonthLabel !== undefined) opts.nextMonthLabel = nextMonthLabel;
    if (nextYearLabel !== undefined) opts.nextYearLabel = nextYearLabel;
    if (cancelLabel !== undefined) opts.cancelLabel = cancelLabel;
    if (applyLabel !== undefined) opts.applyLabel = applyLabel;
    if (calendarLabel !== undefined) opts.calendarLabel = calendarLabel;
    if (dataAttributes !== undefined) opts.dataAttributes = dataAttributes;
    return opts;
  });

  const kit = $derived(createDatePickerRecipe(recipeOptions));
  const mergedClass = $derived(mergeClass(kit.className, className));
</script>

<section class={mergedClass} aria-label={kit.labels.calendar} {...kit.dataAttributes}>
  <header class={kit.slots.headerClassName}>
    <div class={kit.slots.navGroupClassName}>
      <button type="button" class={kit.slots.navButtonClassName} aria-label={kit.labels.previousYear} onclick={onpreviousyear}>«</button>
      <button type="button" class={kit.slots.navButtonClassName} aria-label={kit.labels.previousMonth} onclick={onpreviousmonth}>‹</button>
    </div>
    <div class={kit.slots.monthLabelClassName}>{kit.monthLabel}</div>
    <div class={kit.slots.navGroupClassName}>
      <button type="button" class={kit.slots.navButtonClassName} aria-label={kit.labels.nextMonth} onclick={onnextmonth}>›</button>
      <button type="button" class={kit.slots.navButtonClassName} aria-label={kit.labels.nextYear} onclick={onnextyear}>»</button>
    </div>
  </header>

  <table class={kit.slots.gridClassName} aria-label={kit.monthLabel}>
    <thead>
      <tr class="mw-date-picker__weekdays">
        {#each kit.weekdayLabels as weekday (weekday)}
          <th class={kit.slots.weekdayClassName} scope="col">{weekday}</th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#each kit.weeks as week, weekIndex}
        <tr class={kit.slots.weekClassName}>
          {#each week as day, dayIndex}
            {@const dayKit = kit.dayKits[weekIndex]?.[dayIndex]}
            {#if dayKit}
              <td class={kit.slots.cellClassName}>
                <button
                  type="button"
                  class={dayKit.className}
                  aria-label={dayKit.ariaLabel}
                  aria-pressed={dayKit.selected ? "true" : undefined}
                  disabled={dayKit.disabled}
                  onclick={() => ondayselect?.(day)}
                  {...dayKit.dataAttributes}
                >
                  {day.label}
                </button>
              </td>
            {/if}
          {/each}
        </tr>
      {/each}
    </tbody>
  </table>

  <footer class={kit.slots.footerClassName}>
    <button type="button" class={kit.slots.footerButtonClassName} onclick={oncancel}>
      {kit.labels.cancel}
    </button>
    {#if kit.labels.apply}
      <button type="button" class="{kit.slots.footerButtonClassName} mw-date-picker__footer-button--primary" onclick={onapply}>
        {kit.labels.apply}
      </button>
    {/if}
  </footer>
</section>
