// packages/react/src/components/date-picker/date-picker-field.tsx
import { buildInputFieldA11yIds } from "@marwes-ui/core"
import * as React from "react"
import { Text } from "../text"
import { DatePicker } from "./date-picker"
import type { DatePickerProps } from "./date-picker"

export type DatePickerFieldProps = {
  /** Optional: if omitted, a stable id is generated via useId(). */
  id?: string

  /** Field label (required for accessibility). */
  label: string

  /** Optional helper text shown below the calendar. */
  helperText?: string

  /** Optional error message. */
  error?: string

  /** Props forwarded to the DatePicker atom. */
  datePicker?: Omit<DatePickerProps, "ariaLabel" | "ariaLabelledBy" | "calendarLabel">

  /** Additional aria-describedby IDs to merge with internal helper/error IDs. */
  ariaDescribedBy?: string

  className?: string
}

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function hasTextContent(value: string | undefined): boolean {
  return value !== undefined && value.trim().length > 0
}

/**
 * DatePickerField (Molecule)
 *
 * A labeled wrapper around `DatePicker` that:
 * - renders a visible `<label>` wired via `aria-labelledby`
 * - generates a stable id via `useId()` when one isn't provided
 * - optionally renders helper text and error messages
 * - threads `aria-describedby` to the calendar when helper/error are present
 */
export function DatePickerField(props: DatePickerFieldProps): React.ReactElement {
  const reactId = React.useId()
  const id = props.id ?? `mw-date-picker-${reactId}`
  const labelId = `${id}-label`

  const hasHelperText = hasTextContent(props.helperText)
  const hasError = hasTextContent(props.error)

  const {
    helperTextId,
    errorId,
    describedBy: mergedDescribedBy,
  } = buildInputFieldA11yIds({
    id,
    hasHelperText,
    hasError,
    externalDescribedBy: props.ariaDescribedBy,
  })

  const wrapperClass = cx(
    "mw-date-picker-field",
    hasError && "mw-date-picker-field--invalid",
    props.className,
  )

  return (
    <div className={wrapperClass}>
      <span className="mw-date-picker-field__label" id={labelId}>
        <Text variant="label">{props.label}</Text>
      </span>

      <DatePicker
        {...props.datePicker}
        ariaLabelledBy={labelId}
        {...(mergedDescribedBy ? { "aria-describedby": mergedDescribedBy } : {})}
      />

      {hasHelperText && !hasError && (
        <div className="mw-date-picker-field__helper" id={helperTextId}>
          <Text variant="caption">{props.helperText}</Text>
        </div>
      )}

      {hasError && (
        <div className="mw-date-picker-field__error" id={errorId} aria-live="polite">
          <Text variant="caption">{props.error}</Text>
        </div>
      )}
    </div>
  )
}

// packages/svelte/src/lib/components/date-picker/DatePickerField.svelte
<script lang="ts">
  import { buildInputFieldA11yIds } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import Text from "../text/Text.svelte";
  import DatePicker from "./DatePicker.svelte";
  import type { DatePickerFieldProps, DatePickerProps } from "./types.js";

  let {
    id: userProvidedId,
    label,
    helperText,
    error,
    datePicker = {},
    ariaDescribedBy,
    class: className,
  }: DatePickerFieldProps = $props();

  const uniqueId = $props.id();
  const fieldId = $derived(userProvidedId ?? `mw-date-picker-${uniqueId}`);
  const labelId = $derived(`${fieldId}-label`);

  function hasTextContent(text: string | undefined): boolean {
    return text !== undefined && text.trim().length > 0;
  }

  const hasHelperText = $derived(hasTextContent(helperText));
  const hasError = $derived(hasTextContent(error));

  const a11yIds = $derived(
    buildInputFieldA11yIds({
      id: fieldId,
      hasHelperText,
      hasError,
      externalDescribedBy: ariaDescribedBy,
    })
  );

  const wrapperClass = $derived(
    mergeClass("mw-date-picker-field", hasError && "mw-date-picker-field--invalid", className)
  );

  const datePickerProps = $derived.by((): DatePickerProps => {
    const props: DatePickerProps = {
      ...datePicker,
      ariaLabelledBy: labelId,
    };
    if (a11yIds.describedBy) {
      props.ariaDescribedBy = a11yIds.describedBy;
    }
    return props;
  });
</script>

<div class={wrapperClass}>
  <span class="mw-date-picker-field__label" id={labelId}>
    <Text variant="label">{label}</Text>
  </span>

  <DatePicker {...datePickerProps} />

  {#if hasHelperText && !hasError}
    <div class="mw-date-picker-field__helper" id={a11yIds.helperTextId}>
      <Text variant="caption">{helperText}</Text>
    </div>
  {/if}

  {#if hasError}
    <div class="mw-date-picker-field__error" id={a11yIds.errorId} aria-live="polite">
      <Text variant="caption">{error}</Text>
    </div>
  {/if}
</div>
