// packages/svelte/src/lib/components/breadcrumb/Breadcrumb.svelte
<script lang="ts">
  import { IconName, createBreadcrumbRecipe, toBreadcrumbItemHtmlAttributes, toBreadcrumbHomeHtmlAttributes, toBreadcrumbHtmlAttributes, toBreadcrumbListHtmlAttributes, toBreadcrumbSeparatorHtmlAttributes } from "@marwes-ui/core";
  import Icon from "../icon/Icon.svelte";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { BreadcrumbItem, BreadcrumbProps } from "./types.js";

  let {
    items,
    ariaLabel,
    showHome,
    homeHref,
    homeLabel,
    dataAttributes,
    onitemselect,
    onhomeclick,
    class: className,
  }: BreadcrumbProps = $props();

  const breadcrumbOptions = $derived.by(() => {
    const options = { items };
    if (ariaLabel !== undefined) Object.assign(options, { ariaLabel });
    if (showHome !== undefined) Object.assign(options, { showHome });
    if (homeHref !== undefined) Object.assign(options, { homeHref });
    if (homeLabel !== undefined) Object.assign(options, { homeLabel });
    if (dataAttributes !== undefined) Object.assign(options, { dataAttributes });
    return options;
  });
  const kit = $derived(createBreadcrumbRecipe(breadcrumbOptions));
  const mergedClass = $derived(mergeClass(kit.className, className));

  function sourceItem(item: (typeof kit.items)[number]): BreadcrumbItem {
    return (
      (item.kind === "item" ? item.item : undefined) ?? {
        label: item.label,
        ...(item.value ? { value: item.value } : {}),
        ...(item.href ? { href: item.href } : {}),
        current: item.current,
      }
    );
  }
</script>

<nav class={mergedClass} {...toBreadcrumbHtmlAttributes(kit.a11y)} {...kit.dataAttributes}>
  <ol class={kit.list.className} {...toBreadcrumbListHtmlAttributes(kit.list.a11y)}>
    {#each kit.items as item, index (item.key)}
      <li class={item.className} {...item.dataAttributes}>
        {#if index > 0}
          <span class={kit.separator.className} {...toBreadcrumbSeparatorHtmlAttributes(kit.separator.a11y)}>
            <Icon name={IconName.ChevronRight} decorative size={12} />
          </span>
        {/if}

        {#if item.kind === "home"}
          {#if item.href}
            <a
              class={item.actionClassName}
              href={item.href}
              {...toBreadcrumbHomeHtmlAttributes(item.a11y)}
              aria-current={item.current ? "page" : undefined}
              onclick={() => onhomeclick?.()}
            >
              <Icon name={IconName.Home} decorative size={14} />
            </a>
          {:else if !item.current}
            <button
              type="button"
              class={item.actionClassName}
              {...toBreadcrumbHomeHtmlAttributes(item.a11y)}
              aria-current={item.current ? "page" : undefined}
              onclick={() => onhomeclick?.()}
            >
              <Icon name={IconName.Home} decorative size={14} />
            </button>
          {:else}
            <span
              class={item.actionClassName}
              {...toBreadcrumbHomeHtmlAttributes(item.a11y)}
              aria-current={item.current ? "page" : undefined}
            >
              <Icon name={IconName.Home} decorative size={14} />
            </span>
          {/if}
        {:else if item.current}
          <span
            class={item.actionClassName}
            {...toBreadcrumbItemHtmlAttributes(item.a11y)}
          >
            {item.label}
          </span>
        {:else if item.href}
          <a
            class={item.actionClassName}
            href={item.href}
            {...toBreadcrumbItemHtmlAttributes(item.a11y)}
            onclick={() => onitemselect?.(item.value ?? item.label, sourceItem(item))}
          >
            {item.label}
          </a>
        {:else}
          <button
            type="button"
            class={item.actionClassName}
            {...toBreadcrumbItemHtmlAttributes(item.a11y)}
            onclick={() => onitemselect?.(item.value ?? item.label, sourceItem(item))}
          >
            {item.label}
          </button>
        {/if}
      </li>
    {/each}
  </ol>
</nav>

// packages/react/src/components/breadcrumb/breadcrumb.tsx
import {
  IconName,
  createBreadcrumbRecipe,
  toBreadcrumbHomeHtmlAttributes,
  toBreadcrumbHtmlAttributes,
  toBreadcrumbItemHtmlAttributes,
  toBreadcrumbListHtmlAttributes,
  toBreadcrumbSeparatorHtmlAttributes,
} from "@marwes-ui/core"
import type { BreadcrumbItem, BreadcrumbOptions } from "@marwes-ui/core"
import type * as React from "react"
import { toReactAttributes } from "../../internal/react-attributes"
import { Icon } from "../icon"

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

export interface BreadcrumbProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "children">,
    BreadcrumbOptions {
  items: readonly BreadcrumbItem[]
  onItemSelect?: (
    value: string,
    item: BreadcrumbItem,
    event: React.MouseEvent<HTMLAnchorElement | HTMLButtonElement>,
  ) => void
  onHomeClick?: (event: React.MouseEvent<HTMLAnchorElement | HTMLButtonElement>) => void
}

export function Breadcrumb(props: BreadcrumbProps): React.ReactElement {
  const {
    items,
    ariaLabel,
    showHome,
    homeHref,
    homeLabel,
    dataAttributes,
    onItemSelect,
    onHomeClick,
    className,
    ...restProps
  } = props
  const kit = createBreadcrumbRecipe({
    items,
    ...(ariaLabel !== undefined ? { ariaLabel } : {}),
    ...(showHome !== undefined ? { showHome } : {}),
    ...(homeHref !== undefined ? { homeHref } : {}),
    ...(homeLabel !== undefined ? { homeLabel } : {}),
    ...(dataAttributes !== undefined ? { dataAttributes } : {}),
  })

  return (
    <nav
      {...restProps}
      {...kit.dataAttributes}
      className={cx(kit.className, className)}
      {...toReactAttributes(toBreadcrumbHtmlAttributes(kit.a11y))}
    >
      <ol
        className={kit.list.className}
        {...toReactAttributes(toBreadcrumbListHtmlAttributes(kit.list.a11y))}
      >
        {kit.items.map((item, index) => (
          <li key={item.key} className={item.className} {...item.dataAttributes}>
            {index > 0 && (
              <span
                className={kit.separator.className}
                {...toReactAttributes(toBreadcrumbSeparatorHtmlAttributes(kit.separator.a11y))}
              >
                <Icon name={IconName.ChevronRight} decorative size={12} />
              </span>
            )}
            {item.kind === "home" ? (
              renderHomeItem(item, onHomeClick)
            ) : (
              <BreadcrumbAction item={item} onItemSelect={onItemSelect} />
            )}
          </li>
        ))}
      </ol>
    </nav>
  )
}

function renderHomeItem(
  item: Extract<ReturnType<typeof createBreadcrumbRecipe>["items"][number], { kind: "home" }>,
  onHomeClick: BreadcrumbProps["onHomeClick"],
): React.ReactElement {
  const commonProps = {
    className: item.actionClassName,
    ...toReactAttributes(toBreadcrumbHomeHtmlAttributes(item.a11y)),
    "aria-current": item.current ? ("page" as const) : undefined,
  }

  if (item.href) {
    return (
      <a
        {...commonProps}
        href={item.href}
        onClick={(event) => {
          onHomeClick?.(event)
        }}
      >
        <Icon name={IconName.Home} decorative size={14} />
      </a>
    )
  }

  if (onHomeClick && !item.current) {
    return (
      <button type="button" {...commonProps} onClick={onHomeClick}>
        <Icon name={IconName.Home} decorative size={14} />
      </button>
    )
  }

  return (
    <span {...commonProps}>
      <Icon name={IconName.Home} decorative size={14} />
    </span>
  )
}

interface BreadcrumbActionProps {
  item: Extract<ReturnType<typeof createBreadcrumbRecipe>["items"][number], { kind: "item" }>
  onItemSelect?: BreadcrumbProps["onItemSelect"]
}

function BreadcrumbAction({ item, onItemSelect }: BreadcrumbActionProps): React.ReactElement {
  const sourceItem = item.item ?? {
    label: item.label,
    ...(item.value ? { value: item.value } : {}),
    ...(item.href ? { href: item.href } : {}),
    current: item.current,
  }
  const commonProps = {
    className: item.actionClassName,
    ...toReactAttributes(toBreadcrumbItemHtmlAttributes(item.a11y)),
  }

  if (item.current) {
    return <span {...commonProps}>{item.label}</span>
  }

  if (item.href) {
    return (
      <a
        {...commonProps}
        href={item.href}
        onClick={(event) => {
          onItemSelect?.(item.value ?? item.label, sourceItem, event)
        }}
      >
        {item.label}
      </a>
    )
  }

  return (
    <button
      type="button"
      {...commonProps}
      onClick={(event) => {
        onItemSelect?.(item.value ?? item.label, sourceItem, event)
      }}
    >
      {item.label}
    </button>
  )
}
