// packages/svelte/src/lib/components/segmented-control/SegmentedControl.svelte
<script lang="ts">
  import {
    createSegmentedControlRecipe,
    createSegmentedControlItemRecipe,
    moveSegmentedControlSelection,
    resolveSegmentedControlValue,
  } from "@marwes-ui/core";
  import type { SegmentedControlItemState } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { SegmentedControlProps } from "./types.js";

  let {
    items,
    value: controlledValue,
    defaultValue,
    onvaluechange,
    variant,
    size,
    disabled,
    ariaLabel,
    ariaLabelledBy,
    label,
    class: className,
    id,
    style,
  }: SegmentedControlProps = $props();

  const itemStates: SegmentedControlItemState[] = $derived(
    items.map((item) => ({ value: item.value, ...(item.disabled ? { disabled: true } : {}) }))
  );

  let internalValue = $state<string | undefined>(undefined);

  $effect(() => {
    if (internalValue === undefined) {
      internalValue = resolveSegmentedControlValue(itemStates, defaultValue);
    }
  });

  const resolvedValue = $derived(
    controlledValue !== undefined
      ? resolveSegmentedControlValue(itemStates, controlledValue)
      : internalValue
  );

  function selectItem(nextValue: string): void {
    const resolved = resolveSegmentedControlValue(itemStates, nextValue);
    if (!resolved || resolved === resolvedValue) return;

    if (controlledValue === undefined) {
      internalValue = resolved;
    }
    onvaluechange?.(resolved);
  }

  function handleKeydown(e: KeyboardEvent): void {
    let direction: "next" | "previous" | "start" | "end" | undefined;
    if (e.key === "ArrowRight") direction = "next";
    else if (e.key === "ArrowLeft") direction = "previous";
    else if (e.key === "Home") direction = "start";
    else if (e.key === "End") direction = "end";

    if (!direction) return;
    e.preventDefault();

    const next = moveSegmentedControlSelection(itemStates, resolvedValue, direction);
    if (next) {
      selectItem(next);
      const container = e.currentTarget as HTMLElement;
      const btn = container.querySelector<HTMLButtonElement>(`[data-value="${next}"]`);
      btn?.focus();
    }
  }

  const trackKit = $derived(
    createSegmentedControlRecipe({ value: resolvedValue, variant, size, disabled, ariaLabel, ariaLabelledBy, label })
  );
  const mergedClass = $derived(mergeClass(trackKit.className, className));
</script>

<div
  {id}
  class={mergedClass}
  role={trackKit.a11y.role}
  aria-label={trackKit.a11y.ariaLabel}
  aria-labelledby={trackKit.a11y.ariaLabelledBy}
  aria-disabled={trackKit.a11y.ariaDisabled}
  onkeydown={handleKeydown}
  style={style}
>
  {#each items as item}
    {@const isSelected = item.value === resolvedValue}
    {@const isItemDisabled = disabled || item.disabled}
    {@const itemKit = createSegmentedControlItemRecipe({
      value: item.value,
      selected: isSelected,
      disabled: isItemDisabled,
      ariaLabel: item.ariaLabel,
      iconOnly: item.icon != null && item.label == null,
    })}
    <button
      type="button"
      class={itemKit.className}
      role={itemKit.a11y.role}
      aria-checked={itemKit.a11y.ariaChecked}
      aria-disabled={itemKit.a11y.ariaDisabled}
      aria-label={itemKit.a11y.ariaLabel}
      tabindex={itemKit.a11y.tabIndex}
      disabled={isItemDisabled}
      data-value={item.value}
      onclick={() => !isItemDisabled && selectItem(item.value)}
    >
      {#if item.icon}
        {@render item.icon()}
      {/if}
      {#if item.label}
        {item.label}
      {/if}
    </button>
  {/each}
</div>

// packages/react/src/components/segmented-control/segmented-control.tsx
/**
 * React adapter for Marwes SegmentedControl.
 * Single-select segmented toggle using radiogroup semantics.
 */

import {
  createSegmentedControlItemRecipe,
  createSegmentedControlRecipe,
  moveSegmentedControlSelection,
  resolveSegmentedControlValue,
} from "@marwes-ui/core"
import type {
  SegmentedControlItemState,
  SegmentedControlSize,
  SegmentedControlVariant,
} from "@marwes-ui/core"
import * as React from "react"

export interface SegmentedControlItem {
  value: string
  label?: React.ReactNode
  icon?: React.ReactNode
  disabled?: boolean
  ariaLabel?: string
}

export interface SegmentedControlProps {
  items: SegmentedControlItem[]
  value?: string
  defaultValue?: string
  onValueChange?: (value: string) => void
  variant?: SegmentedControlVariant
  size?: SegmentedControlSize
  disabled?: boolean
  ariaLabel?: string
  ariaLabelledBy?: string
  className?: string
  id?: string
  style?: React.CSSProperties
}

function toItemState(item: SegmentedControlItem): SegmentedControlItemState {
  const state: SegmentedControlItemState = { value: item.value }
  if (item.disabled) state.disabled = true
  return state
}

export function SegmentedControl(props: SegmentedControlProps): React.ReactElement {
  const {
    items,
    value: controlledValue,
    defaultValue,
    onValueChange,
    variant,
    size,
    disabled,
    ariaLabel,
    ariaLabelledBy,
    className,
    id,
    style,
  } = props

  const itemStates = React.useMemo<SegmentedControlItemState[]>(
    () => items.map(toItemState),
    [items],
  )

  const isControlled = controlledValue !== undefined
  const [internalValue, setInternalValue] = React.useState<string | undefined>(() =>
    resolveSegmentedControlValue(itemStates, defaultValue),
  )

  const resolvedValue = React.useMemo(
    () => resolveSegmentedControlValue(itemStates, isControlled ? controlledValue : internalValue),
    [itemStates, isControlled, controlledValue, internalValue],
  )

  const selectItem = React.useCallback(
    (nextValue: string | undefined) => {
      const resolved = resolveSegmentedControlValue(itemStates, nextValue)
      if (!resolved || resolved === resolvedValue) return

      if (!isControlled) setInternalValue(resolved)
      onValueChange?.(resolved)
    },
    [itemStates, isControlled, resolvedValue, onValueChange],
  )

  const handleKeyDown = React.useCallback(
    (event: React.KeyboardEvent<HTMLDivElement>) => {
      let direction: "next" | "previous" | "start" | "end" | undefined

      switch (event.key) {
        case "ArrowRight":
          direction = "next"
          break
        case "ArrowLeft":
          direction = "previous"
          break
        case "Home":
          direction = "start"
          break
        case "End":
          direction = "end"
          break
        default:
          return
      }

      event.preventDefault()
      const nextValue = moveSegmentedControlSelection(itemStates, resolvedValue, direction)
      if (nextValue) {
        selectItem(nextValue)
        const btn = event.currentTarget.querySelector<HTMLButtonElement>(
          `[data-value="${nextValue}"]`,
        )
        btn?.focus()
      }
    },
    [itemStates, resolvedValue, selectItem],
  )

  const trackKit = createSegmentedControlRecipe({
    value: resolvedValue,
    variant,
    size,
    disabled,
    ariaLabel,
    ariaLabelledBy,
  })
  const trackClassName = [trackKit.className, className].filter(Boolean).join(" ")

  return (
    <div
      id={id}
      className={trackClassName}
      role={trackKit.a11y.role}
      aria-label={trackKit.a11y.ariaLabel}
      aria-labelledby={trackKit.a11y.ariaLabelledBy}
      aria-disabled={trackKit.a11y.ariaDisabled}
      onKeyDown={handleKeyDown}
      style={style}
    >
      {items.map((item) => {
        const isSelected = item.value === resolvedValue
        const isItemDisabled = disabled || item.disabled
        const isIconOnly = item.icon != null && item.label == null
        const itemKit = createSegmentedControlItemRecipe({
          value: item.value,
          selected: isSelected,
          disabled: isItemDisabled,
          ariaLabel: item.ariaLabel,
          iconOnly: isIconOnly,
        })

        return (
          <button
            key={item.value}
            type="button"
            className={itemKit.className}
            role={itemKit.a11y.role}
            aria-checked={itemKit.a11y.ariaChecked}
            aria-disabled={itemKit.a11y.ariaDisabled}
            aria-label={itemKit.a11y.ariaLabel}
            tabIndex={itemKit.a11y.tabIndex}
            disabled={isItemDisabled}
            data-value={item.value}
            onClick={() => selectItem(item.value)}
          >
            {item.icon}
            {item.label}
          </button>
        )
      })}
    </div>
  )
}
