// packages/svelte/src/lib/components/slider/SliderField.svelte
<script lang="ts">
  import { buildSliderFieldA11yIds } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import Text from "../text/Text.svelte";
  import Slider from "./Slider.svelte";
  import type { SliderFieldProps, SliderProps } from "./types.js";

  let {
    id: userProvidedId,
    label,
    description,
    helperText,
    error,
    slider = {},
    ariaDescribedBy,
    minValueLabel,
    maxValueLabel,
    labelPosition = "top",
    showEdgeValues = true,
    dataAttributes,
    value = $bindable(),
    class: className,
  }: SliderFieldProps = $props();

  const uniqueId = $props.id();
  const fieldId = $derived(userProvidedId ?? `mw-slider-${uniqueId}`);

  function hasTextContent(text: string | undefined): boolean {
    return text !== undefined && text.trim().length > 0;
  }

  const descriptionText = $derived(description ?? helperText);
  const hasDescription = $derived(hasTextContent(descriptionText));
  const hasError = $derived(hasTextContent(error));
  const isDisabled = $derived(slider.disabled === true);
  const minEdgeValue = $derived(minValueLabel ?? `${slider.min ?? 0}`);
  const maxEdgeValue = $derived(maxValueLabel ?? `${slider.max ?? 100}`);

  const a11yIds = $derived(
    buildSliderFieldA11yIds({ id: fieldId, hasDescription, hasError, externalDescribedBy: ariaDescribedBy })
  );

  const wrapperClass = $derived(
    mergeClass(
      "mw-slider-field",
      labelPosition === "top" && "mw-slider-field--label-top",
      labelPosition === "inline" && "mw-slider-field--label-inline",
      isDisabled && "mw-slider-field--disabled",
      hasError && "mw-slider-field--invalid",
      className
    )
  );
</script>

<div class={wrapperClass} data-label-position={labelPosition} {...dataAttributes}>
  <div class="mw-slider-field__header">
    <div class="mw-slider-field__label" id={a11yIds.labelId}>
      <Text variant="label">{label}</Text>
    </div>
  </div>

  {#if hasDescription && !hasError}
    <div class="mw-slider-field__description" id={a11yIds.descriptionId}>
      <Text variant="caption">{descriptionText}</Text>
    </div>
  {/if}

  {#if labelPosition === "top" && showEdgeValues}
    <div class="mw-slider-field__values-row">
      <span class="mw-slider-field__edge-value mw-slider-field__edge-value--min">
        <Text variant="caption">{minEdgeValue}</Text>
      </span>
      <span class="mw-slider-field__edge-value mw-slider-field__edge-value--max">
        <Text variant="caption">{maxEdgeValue}</Text>
      </span>
    </div>
  {/if}

  <div class="mw-slider-field__control-row">
    {#if labelPosition === "inline" && showEdgeValues}
      <span class="mw-slider-field__edge-value mw-slider-field__edge-value--min">
        <Text variant="caption">{minEdgeValue}</Text>
      </span>
    {/if}

    <div class="mw-slider-field__slider">
      <Slider
        {...slider}
        id={fieldId}
        ariaLabelledBy={a11yIds.labelId}
        ariaDescribedBy={a11yIds.describedBy || undefined}
        invalid={hasError}
        style="width: 100%;"
        bind:value
      />
    </div>

    {#if labelPosition === "inline" && showEdgeValues}
      <span class="mw-slider-field__edge-value mw-slider-field__edge-value--max">
        <Text variant="caption">{maxEdgeValue}</Text>
      </span>
    {/if}
  </div>

  {#if hasDescription && hasError}
    <div class="mw-slider-field__description" id={a11yIds.descriptionId}>
      <Text variant="caption">{descriptionText}</Text>
    </div>
  {/if}

  {#if hasError}
    <div class="mw-slider-field__error" id={a11yIds.errorId} aria-live="polite">
      <Text variant="caption">{error}</Text>
    </div>
  {/if}
</div>

// packages/react/src/components/slider/slider-field.tsx
import { buildSliderFieldA11yIds } from "@marwes-ui/core"
import * as React from "react"
import { Text } from "../text"
import { Slider } from "./slider"
import type { SliderProps } from "./slider"

export type SliderFieldLabelPosition = "top" | "inline"

export type SliderFieldProps = {
  id?: string
  label: React.ReactNode
  description?: React.ReactNode
  error?: React.ReactNode
  slider: SliderProps
  ariaDescribedBy?: string
  minValueLabel?: React.ReactNode
  maxValueLabel?: React.ReactNode
  labelPosition?: SliderFieldLabelPosition
  showEdgeValues?: boolean
  dataAttributes?: Record<string, string>
}

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function hasContent(value: React.ReactNode | undefined): boolean {
  if (value === undefined || value === null || value === false) {
    return false
  }

  if (typeof value === "string") {
    return value.trim().length > 0
  }

  return true
}

function resolveEdgeValueLabel(
  value: React.ReactNode | undefined,
  fallback: number,
): React.ReactNode {
  return value ?? `${fallback}`
}

export function SliderField(props: SliderFieldProps): React.ReactElement {
  const reactId = React.useId()
  const id = props.id ?? `mw-slider-${reactId}`
  const hasDescription = hasContent(props.description)
  const hasError = hasContent(props.error)
  const { labelId, descriptionId, errorId, describedBy } = buildSliderFieldA11yIds({
    id,
    hasDescription,
    hasError,
    externalDescribedBy: props.ariaDescribedBy,
  })

  const disabled = props.slider.disabled || false
  const labelPosition = props.labelPosition ?? "top"
  const showEdgeValues = props.showEdgeValues !== false
  const minValue = props.slider.min ?? 0
  const maxValue = props.slider.max ?? 100
  const minValueLabel = resolveEdgeValueLabel(props.minValueLabel, minValue)
  const maxValueLabel = resolveEdgeValueLabel(props.maxValueLabel, maxValue)
  const wrapperClass = cx(
    "mw-slider-field",
    labelPosition === "top" && "mw-slider-field--label-top",
    labelPosition === "inline" && "mw-slider-field--label-inline",
    disabled && "mw-slider-field--disabled",
    hasError && "mw-slider-field--invalid",
  )

  const {
    ariaLabel: _ignoredAriaLabel,
    ariaLabelledBy: _ignoredAriaLabelledBy,
    ariaDescribedBy: _ignoredAriaDescribedBy,
    style: sliderStyle,
    ...sliderProps
  } = props.slider

  const renderEdgeValue = (position: "min" | "max", value: React.ReactNode): React.ReactElement => (
    <span className={`mw-slider-field__edge-value mw-slider-field__edge-value--${position}`}>
      <Text variant="caption">{value}</Text>
    </span>
  )

  return (
    <div className={wrapperClass} data-label-position={labelPosition} {...props.dataAttributes}>
      <div className="mw-slider-field__header">
        <div className="mw-slider-field__label" id={labelId}>
          <Text variant="label">{props.label}</Text>
        </div>
      </div>

      {hasDescription && (
        <div className="mw-slider-field__description" id={descriptionId}>
          <Text variant="caption">{props.description}</Text>
        </div>
      )}

      {labelPosition === "top" && showEdgeValues ? (
        <div className="mw-slider-field__values-row">
          {renderEdgeValue("min", minValueLabel)}
          {renderEdgeValue("max", maxValueLabel)}
        </div>
      ) : null}

      <div className="mw-slider-field__control-row">
        {labelPosition === "inline" && showEdgeValues
          ? renderEdgeValue("min", minValueLabel)
          : null}

        <div className="mw-slider-field__slider">
          <Slider
            {...sliderProps}
            id={id}
            ariaLabelledBy={labelId}
            {...(describedBy ? { ariaDescribedBy: describedBy } : {})}
            invalid={hasError}
            style={{ width: "100%", ...(sliderStyle ?? {}) }}
          />
        </div>

        {labelPosition === "inline" && showEdgeValues
          ? renderEdgeValue("max", maxValueLabel)
          : null}
      </div>

      {hasError && (
        <div className="mw-slider-field__error" id={errorId} aria-live="polite">
          <Text variant="caption">{props.error}</Text>
        </div>
      )}
    </div>
  )
}
