// packages/react/src/components/input/input-otp.tsx
import {
  buildInputFieldA11yIds,
  createInputOtpRecipe,
  sanitizeInputOtpValue,
} from "@marwes-ui/core"
import type { CssVars, InputOtpOptions } from "@marwes-ui/core"
import * as React from "react"
import { Text } from "../text"

type StyleWithVars = React.CSSProperties & CssVars

export type InputOtpProps = Omit<InputOtpOptions, "describedBy"> & {
  label: string
  helperText?: string
  error?: string
  ariaDescribedBy?: string
  onValueChange?: (value: string) => void
  className?: string
}

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function hasTextContent(value: string | undefined): boolean {
  return value !== undefined && value.trim().length > 0
}

export function InputOtp(props: InputOtpProps): React.ReactElement {
  const reactId = React.useId()
  const id = props.id ?? `mw-input-otp-${reactId}`
  const otpLength = Math.max(1, props.length ?? 6)
  const hasHelperText = hasTextContent(props.helperText)
  const hasError = hasTextContent(props.error)
  const invalid = hasError || props.invalid === true
  const isControlled = props.value !== undefined
  const [uncontrolledValue, setUncontrolledValue] = React.useState(() => {
    return sanitizeInputOtpValue(props.defaultValue, otpLength)
  })

  const currentValue = sanitizeInputOtpValue(
    isControlled ? props.value : uncontrolledValue,
    otpLength,
  )

  const {
    helperTextId,
    errorId,
    describedBy: mergedDescribedBy,
  } = buildInputFieldA11yIds({
    id,
    hasHelperText,
    hasError,
    externalDescribedBy: props.ariaDescribedBy,
  })

  const recipeOptions: InputOtpOptions = {
    id,
    value: currentValue,
    length: otpLength,
    invalid,
  }

  if (props.name) {
    recipeOptions.name = props.name
  }

  if (props.placeholderCharacter) {
    recipeOptions.placeholderCharacter = props.placeholderCharacter
  }

  if (props.disabled) {
    recipeOptions.disabled = true
  }

  if (props.readOnly) {
    recipeOptions.readOnly = true
  }

  if (props.required) {
    recipeOptions.required = true
  }

  if (mergedDescribedBy) {
    recipeOptions.describedBy = mergedDescribedBy
  }

  if (props.ariaLabel) {
    recipeOptions.ariaLabel = props.ariaLabel
  }

  if (props.ariaLabelledBy) {
    recipeOptions.ariaLabelledBy = props.ariaLabelledBy
  }

  const kit = createInputOtpRecipe(recipeOptions)

  const className = cx(kit.className, props.className)
  const style = kit.vars as StyleWithVars

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const nextValue = sanitizeInputOtpValue(event.target.value, otpLength)

    if (!isControlled) {
      setUncontrolledValue(nextValue)
    }

    props.onValueChange?.(nextValue)
  }

  return (
    <div
      className={className}
      style={style}
      data-component="input-otp"
      data-invalid={invalid ? "true" : undefined}
      data-disabled={props.disabled ? "true" : undefined}
    >
      <label className="mw-input-otp__label" htmlFor={id}>
        <Text variant="label">{props.label}</Text>
      </label>

      <div className="mw-input-otp__cells">
        {kit.displayCells.map((displayCell) => (
          <span
            key={displayCell.key}
            className={cx("mw-input-otp__cell", displayCell.filled && "mw-input-otp__cell--filled")}
            aria-hidden="true"
          >
            {displayCell.character}
          </span>
        ))}

        <input
          id={kit.a11y.id}
          className="mw-input-otp__input"
          type="text"
          name={kit.a11y.name}
          inputMode={kit.a11y.inputMode}
          autoComplete={kit.a11y.autoComplete}
          maxLength={kit.a11y.maxLength}
          pattern={kit.a11y.pattern}
          disabled={kit.a11y.disabled}
          readOnly={kit.a11y.readOnly}
          required={kit.a11y.required}
          aria-label={kit.a11y.ariaLabel}
          aria-labelledby={kit.a11y.ariaLabelledBy}
          aria-invalid={kit.a11y.ariaInvalid}
          aria-describedby={kit.a11y.ariaDescribedBy}
          value={kit.displayValue}
          onChange={handleChange}
        />
      </div>

      {hasError ? (
        <div className="mw-input-otp__error" id={errorId} aria-live="polite">
          <Text variant="caption">{props.error}</Text>
        </div>
      ) : hasHelperText ? (
        <div className="mw-input-otp__helper" id={helperTextId}>
          <Text variant="caption">{props.helperText}</Text>
        </div>
      ) : null}
    </div>
  )
}

// packages/svelte/src/lib/components/input/InputOtp.svelte
<script lang="ts">
  import {
    buildInputFieldA11yIds,
    createInputOtpRecipe,
    sanitizeInputOtpValue,
  } from "@marwes-ui/core";
  import type { InputOtpOptions } from "@marwes-ui/core";
  import { cssVarsToStyle } from "../../internal/css-vars.js";
  import { mergeClass } from "../../internal/merge-class.js";
  import Text from "../text/Text.svelte";
  import type { InputOtpProps } from "./types.js";

  let {
    id: userProvidedId,
    name,
    label,
    helperText,
    error,
    ariaDescribedBy,
    value: controlledValue,
    defaultValue,
    length: lengthProp,
    placeholderCharacter,
    disabled,
    readOnly,
    required,
    invalid: invalidProp,
    ariaLabel,
    onvaluechange,
    class: className,
  }: InputOtpProps = $props();

  const uniqueId = $props.id();
  const fieldId = $derived(userProvidedId ?? `mw-input-otp-${uniqueId}`);
  const otpLength = $derived(Math.max(1, lengthProp ?? 6));

  function hasTextContent(text: string | undefined): boolean {
    return text !== undefined && text.trim().length > 0;
  }

  const hasHelperText = $derived(hasTextContent(helperText));
  const hasError = $derived(hasTextContent(error));
  const isInvalid = $derived(hasError || invalidProp === true);
  const isControlled = $derived(controlledValue !== undefined);

  let uncontrolledValue = $state(sanitizeInputOtpValue(defaultValue, lengthProp ?? 6));

  const currentValue = $derived(
    sanitizeInputOtpValue(isControlled ? controlledValue : uncontrolledValue, otpLength)
  );

  const a11yIds = $derived(
    buildInputFieldA11yIds({
      id: fieldId,
      hasHelperText,
      hasError,
      externalDescribedBy: ariaDescribedBy,
    })
  );

  const recipeOptions = $derived.by((): InputOtpOptions => {
    const opts: InputOtpOptions = {
      id: fieldId,
      value: currentValue,
      length: otpLength,
      invalid: isInvalid,
    };
    if (name) opts.name = name;
    if (placeholderCharacter) opts.placeholderCharacter = placeholderCharacter;
    if (disabled) opts.disabled = true;
    if (readOnly) opts.readOnly = true;
    if (required) opts.required = true;
    if (a11yIds.describedBy) opts.describedBy = a11yIds.describedBy;
    if (ariaLabel) opts.ariaLabel = ariaLabel;
    return opts;
  });

  const kit = $derived(createInputOtpRecipe(recipeOptions));
  const mergedClass = $derived(mergeClass(kit.className, className));
  const mergedStyle = $derived(cssVarsToStyle(kit.vars));

  function handleChange(e: Event & { currentTarget: HTMLInputElement }): void {
    const nextValue = sanitizeInputOtpValue(e.currentTarget.value, otpLength);
    if (!isControlled) {
      uncontrolledValue = nextValue;
    }
    onvaluechange?.(nextValue);
  }
</script>

<div
  class={mergedClass}
  style={mergedStyle}
  data-component="input-otp"
  data-invalid={isInvalid ? "true" : undefined}
  data-disabled={disabled ? "true" : undefined}
>
  <label class="mw-input-otp__label" for={fieldId}>
    <Text variant="label">{label}</Text>
  </label>

  <div class="mw-input-otp__cells">
    {#each kit.displayCells as cell (cell.key)}
      <span
        class={mergeClass("mw-input-otp__cell", cell.filled && "mw-input-otp__cell--filled")}
        aria-hidden="true"
      >
        {cell.character}
      </span>
    {/each}

    <input
      id={kit.a11y.id}
      class="mw-input-otp__input"
      type="text"
      name={kit.a11y.name}
      inputmode={kit.a11y.inputMode}
      autocomplete={kit.a11y.autoComplete}
      maxlength={kit.a11y.maxLength}
      pattern={kit.a11y.pattern}
      disabled={kit.a11y.disabled}
      readonly={kit.a11y.readOnly}
      required={kit.a11y.required}
      aria-label={kit.a11y.ariaLabel}
      aria-invalid={kit.a11y.ariaInvalid}
      aria-describedby={kit.a11y.ariaDescribedBy}
      value={kit.displayValue}
      oninput={handleChange}
    />
  </div>

  {#if hasError}
    <div class="mw-input-otp__error" id={a11yIds.errorId} aria-live="polite">
      <Text variant="caption">{error}</Text>
    </div>
  {:else if hasHelperText}
    <div class="mw-input-otp__helper" id={a11yIds.helperTextId}>
      <Text variant="caption">{helperText}</Text>
    </div>
  {/if}
</div>
