// packages/react/src/components/input/select-field.tsx
import {
  IconName,
  buildInputFieldA11yIds,
  resolveSelectComboboxA11y,
  resolveSelectMode,
  resolveSelectOptionA11y,
  toSelectComboboxHtmlAttributes,
  toSelectListboxHtmlAttributes,
  toSelectOptionHtmlAttributes,
} from "@marwes-ui/core"
import * as React from "react"
import { toReactAttributes } from "../../internal/react-attributes"
import { Icon } from "../icon"
import { Text } from "../text"
import { Select } from "./select"
import type { SelectProps } from "./select"
import { SelectArrowIcon } from "./select-arrow-icon"

export type SelectFieldVariant = "default" | "date"

export type SelectFieldProps = {
  id?: string
  label: string
  helperText?: string
  error?: string
  select: SelectProps
  ariaDescribedBy?: string
  variant?: SelectFieldVariant
}

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function hasTextContent(value: string | undefined): boolean {
  return value !== undefined && value.trim().length > 0
}

function getInitialSelectValue(props: SelectProps): string {
  if (props.value !== undefined) {
    return props.value
  }

  if (props.defaultValue !== undefined) {
    return props.defaultValue
  }

  if (props.placeholder !== undefined) {
    return ""
  }

  return props.options[0]?.value ?? ""
}

function getFirstEnabledOptionIndex(options: SelectProps["options"]): number {
  return options.findIndex((option) => !option.disabled)
}

function getLastEnabledOptionIndex(options: SelectProps["options"]): number {
  for (let index = options.length - 1; index >= 0; index -= 1) {
    if (!options[index]?.disabled) {
      return index
    }
  }

  return -1
}

function getSelectedOptionIndex(options: SelectProps["options"], value: string): number {
  return options.findIndex((option) => option.value === value && !option.disabled)
}

function getInitialActiveOptionIndex(options: SelectProps["options"], value: string): number {
  const selectedIndex = getSelectedOptionIndex(options, value)

  if (selectedIndex !== -1) {
    return selectedIndex
  }

  return getFirstEnabledOptionIndex(options)
}

function getNextEnabledOptionIndex(
  options: SelectProps["options"],
  currentIndex: number,
  direction: 1 | -1,
): number {
  if (options.length === 0) {
    return -1
  }

  let nextIndex = currentIndex

  for (let attempts = 0; attempts < options.length; attempts += 1) {
    nextIndex = (nextIndex + direction + options.length) % options.length

    if (!options[nextIndex]?.disabled) {
      return nextIndex
    }
  }

  return currentIndex
}

type MarwesSelectFieldControlProps = {
  id: string
  label?: string
  select: SelectProps
}

function MarwesSelectFieldControl(props: MarwesSelectFieldControlProps): React.ReactElement {
  const { id, label, select } = props
  const isControlled = select.value !== undefined
  const [internalValue, setInternalValue] = React.useState(() => getInitialSelectValue(select))
  const value = isControlled ? (select.value ?? "") : internalValue
  const [open, setOpen] = React.useState(false)
  const [activeIndex, setActiveIndex] = React.useState(() =>
    getInitialActiveOptionIndex(select.options, value),
  )
  const rootRef = React.useRef<HTMLDivElement | null>(null)
  const buttonRef = React.useRef<HTMLButtonElement | null>(null)

  const selectedOption =
    select.options.find((option) => option.value === value) ??
    (select.placeholder === undefined ? select.options[0] : undefined)
  const placeholderSelected = select.placeholder !== undefined && value === ""
  const displayText = placeholderSelected ? select.placeholder : (selectedOption?.label ?? "")
  const comboboxA11y = resolveSelectComboboxA11y({
    id,
    open,
    activeIndex,
    label,
    displayText,
    ariaLabel: select.ariaLabel,
    ariaLabelledBy: select.ariaLabelledBy,
    describedBy: select.describedBy,
    invalid: select.invalid,
    required: select.required,
  })

  React.useEffect(() => {
    if (!open) {
      return
    }

    function handlePointerDown(event: PointerEvent) {
      if (rootRef.current?.contains(event.target as Node)) {
        return
      }

      setOpen(false)
    }

    document.addEventListener("pointerdown", handlePointerDown)

    return () => {
      document.removeEventListener("pointerdown", handlePointerDown)
    }
  }, [open])

  React.useEffect(() => {
    if (!open) {
      return
    }

    setActiveIndex(getInitialActiveOptionIndex(select.options, value))
  }, [open, select.options, value])

  React.useEffect(() => {
    if (!select.disabled) {
      return
    }

    setOpen(false)
  }, [select.disabled])

  const commitValue = (nextValue: string) => {
    if (!isControlled) {
      setInternalValue(nextValue)
    }

    select.onValueChange?.(nextValue)
  }

  const selectOptionAtIndex = (index: number) => {
    const option = select.options[index]

    if (!option || option.disabled) {
      return
    }

    commitValue(option.value)
    setOpen(false)
    buttonRef.current?.focus()
  }

  const handleKeyDown = (event: React.KeyboardEvent<HTMLButtonElement>) => {
    if (select.disabled) {
      return
    }

    switch (event.key) {
      case "ArrowDown": {
        event.preventDefault()

        if (!open) {
          setOpen(true)
          setActiveIndex(getInitialActiveOptionIndex(select.options, value))
          return
        }

        setActiveIndex((currentIndex) => getNextEnabledOptionIndex(select.options, currentIndex, 1))
        return
      }
      case "ArrowUp": {
        event.preventDefault()

        if (!open) {
          setOpen(true)
          setActiveIndex(getInitialActiveOptionIndex(select.options, value))
          return
        }

        setActiveIndex((currentIndex) =>
          getNextEnabledOptionIndex(select.options, currentIndex, -1),
        )
        return
      }
      case "Home": {
        if (!open) {
          return
        }

        event.preventDefault()
        setActiveIndex(getFirstEnabledOptionIndex(select.options))
        return
      }
      case "End": {
        if (!open) {
          return
        }

        event.preventDefault()
        setActiveIndex(getLastEnabledOptionIndex(select.options))
        return
      }
      case "Enter":
      case " ": {
        event.preventDefault()

        if (!open) {
          setOpen(true)
          setActiveIndex(getInitialActiveOptionIndex(select.options, value))
          return
        }

        if (activeIndex !== -1) {
          selectOptionAtIndex(activeIndex)
        }
        return
      }
      case "Escape": {
        if (!open) {
          return
        }

        event.preventDefault()
        setOpen(false)
        return
      }
      case "Tab": {
        setOpen(false)
        return
      }
      default:
        return
    }
  }

  return (
    <div
      ref={rootRef}
      className={cx("mw-select-field__control", open && "mw-select-field__control--open")}
    >
      <button
        ref={buttonRef}
        id={id}
        type="button"
        className={cx(
          "mw-select-field__trigger",
          placeholderSelected && "mw-select-field__trigger--placeholder",
          select.invalid && "is-invalid",
          open && "mw-select-field__trigger--open",
        )}
        {...toReactAttributes(toSelectComboboxHtmlAttributes(comboboxA11y.trigger))}
        disabled={select.disabled}
        data-placeholder-selected={placeholderSelected ? "true" : undefined}
        onClick={() => {
          if (select.disabled) {
            return
          }

          setOpen((currentOpen) => !currentOpen)
        }}
        onKeyDown={handleKeyDown}
      >
        <span className="mw-select-field__trigger-text">{displayText}</span>
        <SelectArrowIcon className="mw-select-field__trigger-icon" />
      </button>

      {select.name ? (
        <input
          aria-hidden="true"
          className="mw-select-field__proxy-input"
          name={select.name}
          type="hidden"
          disabled={select.disabled}
          value={value}
          readOnly
        />
      ) : null}

      {open ? (
        <>
          <div
            className="mw-select-field__list"
            {...toReactAttributes(toSelectListboxHtmlAttributes(comboboxA11y.listbox))}
          >
            {select.options.map((option, optionIndex) => {
              const selected = option.value === value
              const active = optionIndex === activeIndex

              return (
                <div
                  key={option.value}
                  className={cx(
                    "mw-select-field__option",
                    active && "mw-select-field__option--active",
                    selected && "mw-select-field__option--selected",
                    option.disabled && "mw-select-field__option--disabled",
                  )}
                  {...toReactAttributes(
                    toSelectOptionHtmlAttributes(
                      resolveSelectOptionA11y({
                        fieldId: id,
                        index: optionIndex,
                        selected,
                        disabled: option.disabled,
                      }),
                    ),
                  )}
                  onClick={() => selectOptionAtIndex(optionIndex)}
                  onKeyDown={(event) => {
                    if (option.disabled) {
                      return
                    }

                    if (event.key === "Enter" || event.key === " ") {
                      event.preventDefault()
                      selectOptionAtIndex(optionIndex)
                    }
                  }}
                  onMouseDown={(event) => event.preventDefault()}
                  onMouseEnter={() => {
                    if (!option.disabled) {
                      setActiveIndex(optionIndex)
                    }
                  }}
                >
                  <span className="mw-select-field__option-label">{option.label}</span>
                  {selected ? (
                    <Icon
                      className="mw-select-field__option-check"
                      name={IconName.Check}
                      size="xs"
                      decorative
                    />
                  ) : null}
                </div>
              )
            })}
          </div>
        </>
      ) : null}
    </div>
  )
}

export function SelectField(props: SelectFieldProps): React.ReactElement {
  const reactId = React.useId()
  const id = props.id ?? `mw-select-${reactId}`
  const mode = resolveSelectMode(props.select)

  const hasHelperText = hasTextContent(props.helperText)
  const hasError = hasTextContent(props.error)

  const {
    helperTextId,
    errorId,
    describedBy: mergedDescribedBy,
  } = buildInputFieldA11yIds({
    id,
    hasHelperText,
    hasError,
    externalDescribedBy: props.ariaDescribedBy,
  })

  const disabled = props.select.disabled || false
  const invalid = hasError || props.select.invalid || false

  const wrapperClass = cx(
    "mw-input-field",
    "mw-input-field--select",
    mode === "marwes" && "mw-input-field--select-marwes",
    props.variant === "date" && "mw-input-field--select-date",
    disabled && "mw-input-field--disabled",
    invalid && "mw-input-field--invalid",
  )

  const selectProps: SelectProps = {
    ...props.select,
    id,
    invalid,
  }

  if (mergedDescribedBy) {
    selectProps.describedBy = mergedDescribedBy
  }

  return (
    <div className={wrapperClass}>
      <label className="mw-input-field__label" htmlFor={id}>
        <Text variant="label">{props.label}</Text>
      </label>

      <div className="mw-input-field__input-wrapper">
        {mode === "native" ? (
          <Select {...selectProps} native />
        ) : (
          <MarwesSelectFieldControl id={id} label={props.label} select={selectProps} />
        )}
      </div>

      {hasHelperText && !hasError && (
        <div className="mw-input-field__helper" id={helperTextId}>
          <Text variant="caption">{props.helperText}</Text>
        </div>
      )}

      {hasError && (
        <div className="mw-input-field__error" id={errorId} aria-live="polite">
          <Text variant="caption">{props.error}</Text>
        </div>
      )}
    </div>
  )
}

// packages/svelte/src/lib/components/input/SelectField.svelte
<script lang="ts">
  import {
    IconName,
    buildInputFieldA11yIds,
    resolveSelectComboboxA11y,
    resolveSelectMode,
    resolveSelectOptionA11y,
    toSelectComboboxHtmlAttributes,
    toSelectListboxHtmlAttributes,
    toSelectOptionHtmlAttributes,
  } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import Icon from "../icon/Icon.svelte";
  import Text from "../text/Text.svelte";
  import Select from "./Select.svelte";
  import type { SelectFieldProps, SelectProps } from "./types.js";

  function hasTextContent(text: string | undefined): boolean {
    return text !== undefined && text.trim().length > 0;
  }

  function getInitialSelectValue(select: SelectProps): string {
    if (select.value !== undefined) {
      return select.value;
    }

    if (select.defaultValue !== undefined) {
      return select.defaultValue;
    }

    if (select.placeholder !== undefined) {
      return "";
    }

    return select.options[0]?.value ?? "";
  }

  function getFirstEnabledOptionIndex(options: SelectProps["options"]): number {
    return options.findIndex((option) => !option.disabled);
  }

  function getLastEnabledOptionIndex(options: SelectProps["options"]): number {
    for (let index = options.length - 1; index >= 0; index -= 1) {
      if (!options[index]?.disabled) {
        return index;
      }
    }

    return -1;
  }

  function getSelectedOptionIndex(options: SelectProps["options"], currentValue: string): number {
    return options.findIndex((option) => option.value === currentValue && !option.disabled);
  }

  function getInitialActiveOptionIndex(options: SelectProps["options"], currentValue: string): number {
    const selectedIndex = getSelectedOptionIndex(options, currentValue);

    if (selectedIndex !== -1) {
      return selectedIndex;
    }

    return getFirstEnabledOptionIndex(options);
  }

  function getNextEnabledOptionIndex(
    options: SelectProps["options"],
    currentIndex: number,
    direction: 1 | -1
  ): number {
    if (options.length === 0) {
      return -1;
    }

    let nextIndex = currentIndex;

    for (let attempts = 0; attempts < options.length; attempts += 1) {
      nextIndex = (nextIndex + direction + options.length) % options.length;

      if (!options[nextIndex]?.disabled) {
        return nextIndex;
      }
    }

    return currentIndex;
  }

  let {
    id: userProvidedId,
    label,
    helperText,
    error,
    select = { options: [] },
    ariaDescribedBy,
    value = $bindable(getInitialSelectValue(select)),
    variant,
    class: className,
  }: SelectFieldProps = $props();

  const uniqueId = $props.id();
  const fieldId = $derived(userProvidedId ?? `mw-select-${uniqueId}`);
  const mode = $derived(resolveSelectMode(select));
  const hasHelperText = $derived(hasTextContent(helperText));
  const hasError = $derived(hasTextContent(error));
  const invalid = $derived(hasError || select.invalid || false);
  const disabled = $derived(select.disabled || false);

  const a11yIds = $derived(
    buildInputFieldA11yIds({ id: fieldId, hasHelperText, hasError, externalDescribedBy: ariaDescribedBy })
  );

  const wrapperClass = $derived(
    mergeClass(
      "mw-input-field",
      "mw-input-field--select",
      mode === "marwes" && "mw-input-field--select-marwes",
      variant === "date" && "mw-input-field--select-date",
      disabled && "mw-input-field--disabled",
      invalid && "mw-input-field--invalid",
      className
    )
  );

  const mergedSelect = $derived({
    ...select,
    id: fieldId,
    value,
    invalid,
    ...(a11yIds.describedBy ? { describedBy: a11yIds.describedBy } : {}),
  });

  const selectedOption = $derived(
    select.options.find((option) => option.value === value) ??
      (select.placeholder === undefined ? select.options[0] : undefined)
  );
  const placeholderSelected = $derived(select.placeholder !== undefined && value === "");
  const displayText = $derived(placeholderSelected ? (select.placeholder ?? "") : (selectedOption?.label ?? ""));

  let open = $state(false);
  let activeIndex = $state(-1);

  const comboboxA11y = $derived(
    resolveSelectComboboxA11y({
      id: fieldId,
      open,
      activeIndex,
      label,
      displayText,
      ariaLabel: select.ariaLabel,
      ariaLabelledBy: select.ariaLabelledBy,
      describedBy: a11yIds.describedBy,
      invalid,
      required: select.required,
    })
  );
  let controlElement = $state<HTMLDivElement | undefined>(undefined);
  let triggerElement = $state<HTMLButtonElement | undefined>(undefined);

  $effect(() => {
    if (!open) {
      return;
    }

    activeIndex = getInitialActiveOptionIndex(select.options, value);
  });

  $effect(() => {
    if (disabled) {
      open = false;
    }
  });

  $effect(() => {
    if (!open) {
      return;
    }

    function handlePointerDown(event: PointerEvent): void {
      if (controlElement?.contains(event.target as Node)) {
        return;
      }

      open = false;
    }

    document.addEventListener("pointerdown", handlePointerDown);

    return () => {
      document.removeEventListener("pointerdown", handlePointerDown);
    };
  });

  function commitValue(nextValue: string): void {
    value = nextValue;
    select.onvaluechange?.(nextValue);
  }

  function selectOptionAtIndex(index: number): void {
    const option = select.options[index];

    if (!option || option.disabled) {
      return;
    }

    commitValue(option.value);
    open = false;
    triggerElement?.focus();
  }

  function handleTriggerKeydown(event: KeyboardEvent): void {
    if (disabled) {
      return;
    }

    switch (event.key) {
      case "ArrowDown": {
        event.preventDefault();

        if (!open) {
          open = true;
          activeIndex = getInitialActiveOptionIndex(select.options, value);
          return;
        }

        activeIndex = getNextEnabledOptionIndex(select.options, activeIndex, 1);
        return;
      }
      case "ArrowUp": {
        event.preventDefault();

        if (!open) {
          open = true;
          activeIndex = getInitialActiveOptionIndex(select.options, value);
          return;
        }

        activeIndex = getNextEnabledOptionIndex(select.options, activeIndex, -1);
        return;
      }
      case "Home": {
        if (!open) {
          return;
        }

        event.preventDefault();
        activeIndex = getFirstEnabledOptionIndex(select.options);
        return;
      }
      case "End": {
        if (!open) {
          return;
        }

        event.preventDefault();
        activeIndex = getLastEnabledOptionIndex(select.options);
        return;
      }
      case "Enter":
      case " ": {
        event.preventDefault();

        if (!open) {
          open = true;
          activeIndex = getInitialActiveOptionIndex(select.options, value);
          return;
        }

        if (activeIndex !== -1) {
          selectOptionAtIndex(activeIndex);
        }
        return;
      }
      case "Escape": {
        if (!open) {
          return;
        }

        event.preventDefault();
        open = false;
        return;
      }
      case "Tab": {
        open = false;
        return;
      }
      default:
        return;
    }
  }

  function handleOptionKeydown(event: KeyboardEvent, optionIndex: number): void {
    if (event.key !== "Enter" && event.key !== " ") {
      return;
    }

    event.preventDefault();
    selectOptionAtIndex(optionIndex);
  }
</script>

<div class={wrapperClass}>
  <label class="mw-input-field__label" for={fieldId}>
    <Text variant="label">{label}</Text>
  </label>
  <div class="mw-input-field__input-wrapper">
    {#if mode === "native"}
      <Select {...mergedSelect} native={true} bind:value />
    {:else}
      <div
        bind:this={controlElement}
        class={mergeClass("mw-select-field__control", open && "mw-select-field__control--open")}
      >
        <button
          bind:this={triggerElement}
          id={fieldId}
          type="button"
          class={mergeClass(
            "mw-select-field__trigger",
            placeholderSelected && "mw-select-field__trigger--placeholder",
            invalid && "is-invalid",
            open && "mw-select-field__trigger--open"
          )}
          {...toSelectComboboxHtmlAttributes(comboboxA11y.trigger)}
          disabled={disabled}
          data-placeholder-selected={placeholderSelected ? "true" : undefined}
          onclick={() => {
            if (disabled) {
              return;
            }

            open = !open;
          }}
          onkeydown={handleTriggerKeydown}
        >
          <span class="mw-select-field__trigger-text">{displayText}</span>
          <svg
            class="mw-select-field__trigger-icon"
            width="16"
            height="16"
            viewBox="0 0 16 16"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            aria-hidden="true"
            focusable="false"
          >
            <path
              d="M11.5288 5.52876C11.7891 5.26841 12.2111 5.26841 12.4715 5.52876C12.7318 5.78911 12.7318 6.21114 12.4715 6.47147L8.47148 10.4715C8.21115 10.7318 7.78912 10.7318 7.52877 10.4715L3.52876 6.47147C3.26841 6.21112 3.26841 5.78911 3.52876 5.52876C3.78911 5.26841 4.21112 5.26841 4.47147 5.52876L6.58591 7.6432C7.36696 8.42425 8.63329 8.42425 9.41434 7.6432L11.5288 5.52876Z"
              fill="currentColor"
            />
          </svg>
        </button>

        {#if select.name}
          <input
            aria-hidden="true"
            class="mw-select-field__proxy-input"
            name={select.name}
            type="hidden"
            disabled={select.disabled}
            {value}
            readonly
          />
        {/if}

        {#if open}
          <div class="mw-select-field__list" {...toSelectListboxHtmlAttributes(comboboxA11y.listbox)}>
            {#each select.options as option, optionIndex (option.value)}
              {@const selected = option.value === value}
              {@const active = optionIndex === activeIndex}
              <div
                class={mergeClass(
                  "mw-select-field__option",
                  active && "mw-select-field__option--active",
                  selected && "mw-select-field__option--selected",
                  option.disabled && "mw-select-field__option--disabled"
                )}
                {...toSelectOptionHtmlAttributes(
                  resolveSelectOptionA11y({ fieldId, index: optionIndex, selected, disabled: option.disabled })
                )}
                onclick={() => selectOptionAtIndex(optionIndex)}
                onkeydown={(event) => handleOptionKeydown(event, optionIndex)}
                onmousedown={(event) => event.preventDefault()}
                onmouseenter={() => {
                  if (!option.disabled) {
                    activeIndex = optionIndex;
                  }
                }}
              >
                <span class="mw-select-field__option-label">{option.label}</span>
                {#if selected}
                  <Icon class="mw-select-field__option-check" name={IconName.Check} size="xs" decorative />
                {/if}
              </div>
            {/each}
          </div>
        {/if}
      </div>
    {/if}
  </div>
  {#if hasHelperText && !hasError}
    <div class="mw-input-field__helper" id={a11yIds.helperTextId}>
      <Text variant="caption">{helperText}</Text>
    </div>
  {/if}
  {#if hasError}
    <div class="mw-input-field__error" id={a11yIds.errorId} aria-live="polite">
      <Text variant="caption">{error}</Text>
    </div>
  {/if}
</div>
