// packages/react/src/components/input/textarea.tsx
import type { CssVars, TextareaOptions } from "@marwes-ui/core"
import { createTextareaRecipe } from "@marwes-ui/core"
import type * as React from "react"
import { useRenderKitDebug } from "../../hooks/use-renderkit-debug"

type StyleWithVars = React.CSSProperties & CssVars

export type TextareaProps = TextareaOptions & {
  onValueChange?: (value: string) => void
  className?: string
}

export function Textarea(props: TextareaProps) {
  const kit = createTextareaRecipe(props)

  useRenderKitDebug(kit, "Textarea")

  const style = kit.vars as StyleWithVars
  const className = props.className ? `${kit.className} ${props.className}` : kit.className

  const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    props.onValueChange?.(e.target.value)
  }

  return (
    <textarea
      className={className}
      style={style}
      id={kit.a11y.id}
      name={kit.a11y.name}
      inputMode={kit.a11y.inputMode}
      autoComplete={kit.a11y.autoComplete}
      placeholder={kit.a11y.placeholder}
      disabled={kit.a11y.disabled}
      readOnly={kit.a11y.readOnly}
      required={kit.a11y.required}
      rows={kit.a11y.rows}
      cols={kit.a11y.cols}
      aria-label={kit.a11y.ariaLabel}
      aria-labelledby={kit.a11y.ariaLabelledBy}
      aria-invalid={kit.a11y.ariaInvalid}
      aria-describedby={kit.a11y.ariaDescribedBy}
      value={props.value}
      defaultValue={props.defaultValue}
      onChange={handleChange}
    />
  )
}

// packages/svelte/src/lib/components/input/Textarea.svelte
<script lang="ts">
  import { createTextareaRecipe } from "@marwes-ui/core";
  import { cssVarsToStyle, mergeStyle } from "../../internal/css-vars.js";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { TextareaProps } from "./types.js";

  let {
    defaultValue,
    value = $bindable(defaultValue ?? ""),
    oninput,
    class: className,
    style,
    describedBy,
    ...options
  }: TextareaProps = $props();

  const kit = $derived(
    createTextareaRecipe({
      ...options,
      value,
      ...(describedBy ? { describedBy } : {}),
    })
  );
  const mergedClass = $derived(mergeClass(kit.className, className));
  const mergedStyle = $derived(mergeStyle(cssVarsToStyle(kit.vars), style));

  function handleInput(e: Event & { currentTarget: HTMLTextAreaElement }): void {
    value = e.currentTarget.value;
    oninput?.(e);
  }
</script>

<textarea
  class={mergedClass}
  style={mergedStyle}
  id={kit.a11y.id}
  name={kit.a11y.name}
  inputmode={kit.a11y.inputMode}
  autocomplete={kit.a11y.autoComplete as any}
  placeholder={kit.a11y.placeholder}
  disabled={kit.a11y.disabled}
  readonly={kit.a11y.readOnly}
  required={kit.a11y.required}
  rows={kit.a11y.rows}
  cols={kit.a11y.cols}
  aria-label={kit.a11y.ariaLabel}
  aria-labelledby={kit.a11y.ariaLabelledBy}
  aria-invalid={kit.a11y.ariaInvalid}
  aria-describedby={kit.a11y.ariaDescribedBy}
  {value}
  oninput={handleInput}
></textarea>
