// packages/svelte/src/lib/components/checkbox/CheckboxGroupField.svelte
<script lang="ts">
  import {
    buildCheckboxGroupFieldA11yIds,
    resolveCheckboxGroupFieldA11y,
    toCheckboxGroupFieldHtmlAttributes,
  } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import Text from "../text/Text.svelte";
  import type { CheckboxGroupFieldProps } from "./types.js";

  let {
    id: userProvidedId,
    label,
    description,
    error,
    ariaDescribedBy,
    required,
    disabled,
    children,
    class: className,
  }: CheckboxGroupFieldProps = $props();

  const uniqueId = $props.id();
  const fieldId = $derived(userProvidedId ?? `mw-checkbox-group-${uniqueId}`);

  function hasTextContent(text: string | undefined): boolean {
    return text !== undefined && text.trim().length > 0;
  }

  const hasDescription = $derived(hasTextContent(description));
  const hasError = $derived(hasTextContent(error));

  const a11yIds = $derived(
    buildCheckboxGroupFieldA11yIds({
      id: fieldId,
      hasDescription,
      hasError,
      externalDescribedBy: ariaDescribedBy,
    })
  );

  const wrapperClass = $derived(
    mergeClass("mw-checkbox-group-field", disabled && "mw-checkbox-group-field--disabled", hasError && "mw-checkbox-group-field--invalid", className)
  );
</script>

<!-- svelte-ignore a11y_role_supports_aria_props_implicit -->
<fieldset
  class={wrapperClass}
  {...toCheckboxGroupFieldHtmlAttributes(
    resolveCheckboxGroupFieldA11y({ labelId: a11yIds.labelId, describedBy: a11yIds.describedBy, invalid: hasError, required })
  )}
  disabled={disabled ? true : undefined}
>
  <legend class="mw-checkbox-group-field__label" id={a11yIds.labelId}>
    <Text variant="label">{label}</Text>
  </legend>
  {#if hasDescription}
    <div class="mw-checkbox-group-field__description" id={a11yIds.descriptionId}>
      <Text variant="caption">{description}</Text>
    </div>
  {/if}
  <div class="mw-checkbox-group-field__options">
    {@render children?.()}
  </div>
  {#if hasError}
    <div class="mw-checkbox-group-field__error" id={a11yIds.errorId} aria-live="polite">
      <Text variant="caption">{error}</Text>
    </div>
  {/if}
</fieldset>

// packages/react/src/components/checkbox/checkbox-group-field.tsx
import {
  buildCheckboxGroupFieldA11yIds,
  resolveCheckboxGroupFieldA11y,
  toCheckboxGroupFieldHtmlAttributes,
} from "@marwes-ui/core"
import * as React from "react"
import { toReactAttributes } from "../../internal/react-attributes"
import { Text } from "../text"
import { Checkbox, type CheckboxProps } from "./checkbox"

export interface CheckboxGroupFieldOption {
  value: string
  label: React.ReactNode
  description?: React.ReactNode
  disabled?: boolean
  indeterminate?: boolean
}

export type CheckboxGroupFieldCheckboxProps = Omit<
  CheckboxProps,
  | "ariaDescribedBy"
  | "ariaLabel"
  | "ariaLabelledBy"
  | "checked"
  | "defaultChecked"
  | "disabled"
  | "id"
  | "indeterminate"
  | "invalid"
  | "name"
  | "onChange"
  | "onCheckedChange"
  | "required"
  | "value"
>

export interface CheckboxGroupFieldProps {
  label: React.ReactNode
  options: CheckboxGroupFieldOption[]
  description?: React.ReactNode
  error?: React.ReactNode
  value?: string[]
  onChange?: (value: string[]) => void
  defaultValue?: string[]
  checkbox?: CheckboxGroupFieldCheckboxProps
  disabled?: boolean
  required?: boolean
  name?: string
  id?: string
  ariaDescribedBy?: string
  dataAttributes?: Record<string, string>
}

function hasContent(value: React.ReactNode | undefined): boolean {
  if (value === undefined || value === null || value === false) return false
  if (typeof value === "string") return value.trim().length > 0
  return true
}

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function orderSelectedValues(values: string[], options: CheckboxGroupFieldOption[]): string[] {
  const optionValues = new Set(options.map((option) => option.value))
  const selectedValues = new Set(values)
  const knownValues = options
    .map((option) => option.value)
    .filter((value) => selectedValues.has(value))
  const unknownValues = values.filter((value) => !optionValues.has(value))
  return [...knownValues, ...unknownValues]
}

export function CheckboxGroupField(props: CheckboxGroupFieldProps): React.ReactElement {
  const reactId = React.useId()
  const id = props.id ?? `mw-checkbox-group-${reactId}`

  const hasDescription = hasContent(props.description)
  const hasError = hasContent(props.error)
  const isInvalid = hasError

  const { labelId, descriptionId, errorId, describedBy } = buildCheckboxGroupFieldA11yIds({
    id,
    hasDescription,
    hasError,
    externalDescribedBy: props.ariaDescribedBy,
  })

  const isControlled = props.value !== undefined
  const [internalValue, setInternalValue] = React.useState<string[]>(
    orderSelectedValues(props.defaultValue ?? [], props.options),
  )
  const selectedValues = orderSelectedValues(
    isControlled ? (props.value ?? []) : internalValue,
    props.options,
  )
  const selectedValueSet = new Set(selectedValues)

  const handleToggle = (nextValue: string): void => {
    const rawNextValue = selectedValueSet.has(nextValue)
      ? selectedValues.filter((value) => value !== nextValue)
      : [...selectedValues, nextValue]
    const orderedNextValue = orderSelectedValues(rawNextValue, props.options)

    if (!isControlled) {
      setInternalValue(orderedNextValue)
    }

    props.onChange?.(orderedNextValue)
  }

  const wrapperClass = cx(
    "mw-checkbox-group-field",
    props.disabled && "mw-checkbox-group-field--disabled",
    isInvalid && "mw-checkbox-group-field--invalid",
  )

  return (
    <fieldset
      className={wrapperClass}
      {...toReactAttributes(
        toCheckboxGroupFieldHtmlAttributes(
          resolveCheckboxGroupFieldA11y({
            labelId,
            describedBy,
            invalid: isInvalid,
            required: props.required,
          }),
        ),
      )}
      disabled={props.disabled ? true : undefined}
      {...props.dataAttributes}
    >
      <legend className="mw-checkbox-group-field__label" id={labelId}>
        <Text variant="label">{props.label}</Text>
      </legend>

      {hasDescription && (
        <div className="mw-checkbox-group-field__description" id={descriptionId}>
          <Text variant="caption">{props.description}</Text>
        </div>
      )}

      <div className="mw-checkbox-group-field__options">
        {props.options.map((option, index) => {
          const optionId = `${id}-option-${index}`
          const optionLabelId = `${optionId}-label`
          const optionDescriptionId = `${optionId}-description`
          const hasOptionDescription = hasContent(option.description)
          const isOptionDisabled = props.disabled || option.disabled || false
          const checkboxProps: CheckboxProps = {
            ...(props.checkbox ?? {}),
            id: optionId,
            value: option.value,
            ariaLabelledBy: optionLabelId,
            checked: selectedValueSet.has(option.value),
            disabled: isOptionDisabled,
            invalid: isInvalid,
            onCheckedChange: () => handleToggle(option.value),
          }

          if (hasOptionDescription) {
            checkboxProps.ariaDescribedBy = optionDescriptionId
          }

          if (props.name !== undefined) {
            checkboxProps.name = props.name
          }

          if (option.indeterminate !== undefined) {
            checkboxProps.indeterminate = option.indeterminate
          }

          return (
            <label
              key={option.value}
              className={cx(
                "mw-checkbox-group-field__option",
                hasOptionDescription && "mw-checkbox-group-field__option--with-description",
              )}
              htmlFor={optionId}
            >
              <Checkbox {...checkboxProps} />
              <span className="mw-checkbox-group-field__option-content">
                <Text
                  id={optionLabelId}
                  variant="label"
                  className="mw-checkbox-group-field__option-label"
                >
                  {option.label}
                </Text>
                {hasOptionDescription && (
                  <Text
                    id={optionDescriptionId}
                    variant="caption"
                    className="mw-checkbox-group-field__option-description"
                  >
                    {option.description}
                  </Text>
                )}
              </span>
            </label>
          )
        })}
      </div>

      {hasError && (
        <div className="mw-checkbox-group-field__error" id={errorId} aria-live="polite">
          <Text variant="caption">{props.error}</Text>
        </div>
      )}
    </fieldset>
  )
}
