// packages/svelte/src/lib/components/radio/Radio.svelte
<script lang="ts">
  import { radioRecipe } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { RadioProps } from "./types.js";

  let {
    defaultChecked,
    checked = $bindable(defaultChecked ?? false),
    onchange,
    oncheckedchange,
    class: className,
    ...coreProps
  }: RadioProps = $props();

  const kit = $derived(radioRecipe({ ...coreProps, checked }));
  const mergedClass = $derived(mergeClass(kit.className, className));

  function handleChange(e: Event & { currentTarget: HTMLInputElement }): void {
    checked = e.currentTarget.checked;
    onchange?.(e);
    oncheckedchange?.(e.currentTarget.checked);
  }
</script>

<!-- svelte-ignore a11y_role_supports_aria_props_implicit -->
<input
  type="radio"
  class={mergedClass}
  id={kit.a11y.id}
  name={kit.a11y.name}
  value={kit.a11y.value}
  disabled={kit.a11y.disabled === true}
  required={kit.a11y.required === true}
  aria-label={kit.a11y.ariaLabel}
  aria-labelledby={kit.a11y.ariaLabelledBy}
  aria-describedby={kit.a11y.ariaDescribedBy}
  aria-invalid={kit.a11y.ariaInvalid === true ? true : undefined}
  {checked}
  onchange={handleChange}
/>

// packages/react/src/components/radio/radio.tsx
/**
 * React adapter for Marwes Radio.
 * - Renders a native <input type="radio"> using the core render kit.
 * - Applies strict a11y fields and modifier classes.
 */

import { radioRecipe } from "@marwes-ui/core"
import type { RadioOptions } from "@marwes-ui/core"
import type * as React from "react"

export type RadioProps = RadioOptions & {
  /** Called with the next checked value when the user selects this radio. */
  onCheckedChange?: (checked: boolean) => void
  /** Raw event access escape hatch. */
  onChange?: React.ChangeEventHandler<HTMLInputElement>
}

export function Radio(props: RadioProps): React.ReactElement {
  const { onCheckedChange, onChange, ...coreProps } = props
  const kit = radioRecipe(coreProps)
  const { a11y } = kit

  const handleChange: React.ChangeEventHandler<HTMLInputElement> = (e) => {
    onChange?.(e)
    onCheckedChange?.(e.currentTarget.checked)
  }

  return (
    <input
      type="radio"
      className={kit.className}
      id={a11y.id}
      name={a11y.name}
      value={a11y.value}
      disabled={a11y.disabled === true}
      required={a11y.required === true}
      aria-label={a11y.ariaLabel}
      aria-labelledby={a11y.ariaLabelledBy}
      aria-describedby={a11y.ariaDescribedBy}
      aria-invalid={a11y.ariaInvalid === true ? true : undefined}
      checked={kit.checked}
      defaultChecked={kit.defaultChecked}
      onChange={handleChange}
    />
  )
}
