// packages/svelte/src/lib/components/text/Text.svelte
<script lang="ts">
  import { textRecipe, toTextHtmlAttributes } from "@marwes-ui/core";
  import { cssVarsToStyle, mergeStyle } from "../../internal/css-vars.js";
  import { mergeClass } from "../../internal/merge-class.js";
  import { useTheme } from "../../provider/use-theme.js";
  import type { TextProps } from "./types.js";

  let {
    children,
    class: className,
    style,
    ...opts
  }: TextProps = $props();

  const { theme } = useTheme();
  const kit = $derived(textRecipe(opts, theme));
  const mergedClass = $derived(mergeClass(kit.className, className));
  const mergedStyle = $derived(mergeStyle(cssVarsToStyle(kit.vars), style));
</script>

<svelte:element this={kit.tag} {...toTextHtmlAttributes(kit.a11y)} class={mergedClass} style={mergedStyle}>
  {@render children?.()}
</svelte:element>

// packages/react/src/components/text/text.tsx
/**
 * React adapter for Marwes Text component.
 * - Renders non-heading typography styles without creating document outline.
 */

import { textRecipe, toTextHtmlAttributes } from "@marwes-ui/core"
import type { CssVars, TextAs, TextOptions, TextVariant } from "@marwes-ui/core"
import type * as React from "react"
import { toReactAttributes } from "../../internal/react-attributes"
import { useTheme } from "../../provider/use-theme"

type StyleWithVars = React.CSSProperties & CssVars

export type TextProps = TextOptions & {
  /**
   * Visual typography variant.
   * @default "caption"
   */
  variant?: TextVariant

  /**
   * Rendered HTML element.
   * @default "span"
   */
  as?: TextAs

  /**
   * Content of the text node.
   */
  children?: React.ReactNode

  /**
   * Additional CSS class names.
   */
  className?: string

  /**
   * Inline styles.
   */
  style?: React.CSSProperties
}

export function Text(props: TextProps): React.ReactElement {
  const { children, className: customClassName, style: customStyle, ...opts } = props
  const theme = useTheme()
  const kit = textRecipe(opts, theme)
  const Tag = kit.tag

  const style = { ...(kit.vars as StyleWithVars), ...customStyle }
  const className = customClassName ? `${kit.className} ${customClassName}` : kit.className

  return (
    <Tag {...toReactAttributes(toTextHtmlAttributes(kit.a11y))} className={className} style={style}>
      {children}
    </Tag>
  )
}

export type TextComponent = typeof Text
export const TypographyText = Text
