// packages/svelte/src/lib/provider/MarwesProvider.svelte
<script lang="ts">
  import {
    ThemeMode as MwThemeMode,
    createMwTheme,
    nextThemeMode,
    resolveThemeInput,
    resolveThemePreference,
  } from "@marwes-ui/core";
  import type { MwTheme, ResolvedTheme, ThemeMode, ThemePreference } from "@marwes-ui/core";
  import { setMarwesContext } from "./context.js";
  import { applyThemeToElement, loadThemeFonts, themeToRootStyle } from "./runtime-theme.js";
  import {
    applyModeAttribute,
    getSystemThemeMode,
    readStoredThemePreference,
    subscribeToSystemThemeMode,
    withoutModeTransitions,
    writeStoredThemePreference,
  } from "./theme-mode-runtime.js";
  import type { MarwesContextState, MarwesProviderProps } from "./types.js";

  let {
    theme,
    defaultPreference,
    preference: controlledPreference,
    defaultMode,
    mode: controlledMode,
    fontLoading = "auto",
    onPreferenceChange,
    onModeChange,
    storageKey = false,
    enableSystem = true,
    target = "provider",
    attribute = "class",
    disableTransitionOnChange = false,
    variableStrategy = "inline",
    children,
  }: MarwesProviderProps = $props();

  let rootElement: HTMLDivElement | undefined = $state(undefined);

  let internalPreference = $state<ThemePreference>(
    defaultPreference ?? defaultMode ?? MwThemeMode.light
  );

  let systemMode = $state<ThemeMode>(
    enableSystem ? getSystemThemeMode() : MwThemeMode.light
  );

  const activePreference = $derived(
    controlledPreference ?? controlledMode ?? theme?.mode ?? internalPreference
  );

  const activeMode = $derived(resolveThemePreference(activePreference, systemMode));

  const isPreferenceControlled = $derived(
    controlledPreference !== undefined || controlledMode !== undefined || theme?.mode !== undefined
  );

  const resolved: ResolvedTheme = $derived(
    resolveThemeInput({ ...(theme ?? {}), mode: activeMode })
  );

  const mwTheme: MwTheme = $derived(createMwTheme(resolved));

  const rootStyle = $derived(
    variableStrategy === "style-tag" ? undefined : themeToRootStyle(resolved)
  );

  const rootStyleString = $derived(
    rootStyle
      ? Object.entries(rootStyle)
          .map(([k, v]) => (k === "backgroundColor" ? `background-color: ${v}` : `${k}: ${v}`))
          .join("; ")
      : undefined
  );

  function setPreference(nextPreference: ThemePreference): void {
    if (!isPreferenceControlled) {
      internalPreference = nextPreference;
    }
    writeStoredThemePreference(storageKey, nextPreference);
    onPreferenceChange?.(nextPreference);
  }

  function setMode(nextMode: ThemeMode): void {
    setPreference(nextMode);
    onModeChange?.(nextMode);
  }

  function toggleMode(): void {
    setMode(nextThemeMode(activeMode));
  }

  // Context state — mutated reactively by effects below
  const contextState: MarwesContextState = $state({
    theme: resolved,
    mode: activeMode,
    preference: activePreference,
    systemMode,
  });

  setMarwesContext({
    get state() { return contextState; },
    setMode,
    setPreference,
    toggleMode,
  });

  // Keep context state synced with derived values
  $effect(() => {
    contextState.theme = resolved;
    contextState.mode = activeMode;
    contextState.preference = activePreference;
    contextState.systemMode = systemMode;
  });

  // Read stored preference on mount
  $effect(() => {
    const storedPreference = readStoredThemePreference(storageKey);
    if (storedPreference !== undefined && !isPreferenceControlled) {
      internalPreference = storedPreference;
    }
  });

  // System theme subscription
  $effect(() => {
    if (!enableSystem) {
      systemMode = MwThemeMode.light;
      return;
    }

    systemMode = getSystemThemeMode();

    if (activePreference !== "system") {
      return;
    }

    const unsubscribe = subscribeToSystemThemeMode((mode) => {
      systemMode = mode;
    });

    return unsubscribe;
  });

  // Apply theme to element (inline vars)
  $effect(() => {
    if (variableStrategy === "style-tag") return;
    if (rootElement) {
      applyThemeToElement(rootElement, resolved);
    }
  });

  // Apply mode attribute to target
  $effect(() => {
    if (target === "provider") return;

    const apply = () => {
      applyModeAttribute({
        target,
        providerElement: rootElement ?? null,
        mode: activeMode,
        attribute,
      });
    };

    if (disableTransitionOnChange) {
      withoutModeTransitions(apply);
      return;
    }

    apply();
  });

  // Font loading
  $effect(() => {
    loadThemeFonts(resolved, fontLoading);
  });
</script>

<div
  bind:this={rootElement}
  class={`mw-theme--${resolved.mode}`}
  data-marwes-theme="true"
  data-marwes-mode={resolved.mode}
  style={rootStyleString}
>
  {@render children?.({ mwTheme })}
</div>

// packages/react/src/provider/marwes-provider.tsx
import type {
  MarwesProviderOptions,
  MwTheme,
  ResolvedTheme,
  ThemeMode,
  ThemePreference,
} from "@marwes-ui/core"
import {
  ThemeMode as MwThemeMode,
  createMwTheme,
  nextThemeMode,
  resolveThemeInput,
  resolveThemePreference,
} from "@marwes-ui/core"
import * as React from "react"
import { MarwesContext } from "./marwes-context"
import { applyThemeToElement, loadThemeFonts, themeToRootStyle } from "./runtime-theme"
import {
  applyModeAttribute,
  getSystemThemeMode,
  readStoredThemePreference,
  subscribeToSystemThemeMode,
  withoutModeTransitions,
  writeStoredThemePreference,
} from "./theme-mode-runtime"

export type MarwesProviderChildren = React.ReactNode | ((mwTheme: MwTheme) => React.ReactNode)

export interface MarwesProviderProps extends MarwesProviderOptions {
  children: MarwesProviderChildren
}

export function MarwesProvider({
  theme,
  defaultPreference,
  preference: controlledPreference,
  defaultMode,
  mode: controlledMode,
  fontLoading = "auto",
  onPreferenceChange,
  onModeChange,
  storageKey = false,
  enableSystem = true,
  target = "provider",
  attribute = "class",
  disableTransitionOnChange = false,
  variableStrategy = "inline",
  children,
}: MarwesProviderProps) {
  const [providerElement, setProviderElement] = React.useState<HTMLDivElement | null>(null)
  const [internalPreference, setInternalPreference] = React.useState<ThemePreference>(
    defaultPreference ?? defaultMode ?? MwThemeMode.light,
  )
  const [systemMode, setSystemMode] = React.useState<ThemeMode>(() =>
    enableSystem ? getSystemThemeMode() : MwThemeMode.light,
  )

  const activePreference =
    controlledPreference ?? controlledMode ?? theme?.mode ?? internalPreference
  const activeMode = resolveThemePreference(activePreference, systemMode)
  const isPreferenceControlled =
    controlledPreference !== undefined || controlledMode !== undefined || theme?.mode !== undefined

  React.useEffect(() => {
    const storedPreference = readStoredThemePreference(storageKey)
    if (storedPreference !== undefined && !isPreferenceControlled) {
      setInternalPreference(storedPreference)
    }
  }, [isPreferenceControlled, storageKey])

  React.useEffect(() => {
    if (!enableSystem) {
      setSystemMode(MwThemeMode.light)
      return
    }

    setSystemMode(getSystemThemeMode())

    if (activePreference !== "system") {
      return
    }

    return subscribeToSystemThemeMode(setSystemMode)
  }, [activePreference, enableSystem])

  const setPreference = React.useCallback(
    (nextPreference: ThemePreference) => {
      if (!isPreferenceControlled) {
        setInternalPreference(nextPreference)
      }

      writeStoredThemePreference(storageKey, nextPreference)
      onPreferenceChange?.(nextPreference)
    },
    [isPreferenceControlled, onPreferenceChange, storageKey],
  )

  const setMode = React.useCallback(
    (nextMode: ThemeMode) => {
      setPreference(nextMode)
      onModeChange?.(nextMode)
    },
    [onModeChange, setPreference],
  )

  const toggleMode = React.useCallback(() => {
    setMode(nextThemeMode(activeMode))
  }, [activeMode, setMode])

  const resolved: ResolvedTheme = React.useMemo(
    () => resolveThemeInput({ ...(theme ?? {}), mode: activeMode }),
    [activeMode, theme],
  )
  const mwTheme = React.useMemo(() => createMwTheme(resolved), [resolved])
  const renderedChildren = typeof children === "function" ? children(mwTheme) : children
  const rootStyle = React.useMemo(() => {
    if (variableStrategy === "style-tag") return undefined
    return themeToRootStyle(resolved) as React.CSSProperties
  }, [resolved, variableStrategy])

  React.useEffect(() => {
    if (variableStrategy === "style-tag") return
    if (providerElement) {
      applyThemeToElement(providerElement, resolved)
    }
  }, [providerElement, resolved, variableStrategy])

  React.useEffect(() => {
    if (target === "provider") return

    const apply = () => {
      applyModeAttribute({
        target,
        providerElement: null,
        mode: activeMode,
        attribute,
      })
    }

    if (disableTransitionOnChange) {
      withoutModeTransitions(apply)
      return
    }

    apply()
  }, [activeMode, attribute, disableTransitionOnChange, target])

  React.useEffect(() => {
    loadThemeFonts(resolved, fontLoading)
  }, [resolved, fontLoading])

  const contextValue = React.useMemo(
    () => ({
      theme: resolved,
      mode: activeMode,
      preference: activePreference,
      systemMode,
      setMode,
      setPreference,
      toggleMode,
      providerElement,
    }),
    [
      activeMode,
      activePreference,
      providerElement,
      resolved,
      setMode,
      setPreference,
      systemMode,
      toggleMode,
    ],
  )

  return (
    <MarwesContext.Provider value={contextValue}>
      <div
        ref={setProviderElement}
        className={`mw-theme--${resolved.mode}`}
        data-marwes-theme="true"
        data-marwes-mode={resolved.mode}
        data-marwes-personality={resolved.personality}
        style={rootStyle}
      >
        {renderedChildren}
      </div>
    </MarwesContext.Provider>
  )
}
