// apps/storybook-react/src/stories/color/ColorSwatch.tsx
import { useState } from "react"
import "./ColorSwatch.css"
import { Paragraph } from "@marwes-ui/react"

export interface ColorSwatchProps {
  /** Display name of the color */
  name: string
  /** Hex color value */
  hex: string
  /** CSS variable name (e.g., --mw-color-primary-base) */
  cssVar: string
  /** Optional description */
  description?: string
  /** Optional usage examples */
  usage?: string
}

export function ColorSwatch({ name, hex, cssVar, description, usage }: ColorSwatchProps) {
  const [copied, setCopied] = useState<"hex" | "var" | null>(null)

  const copyToClipboard = (text: string, type: "hex" | "var") => {
    navigator.clipboard.writeText(text)
    setCopied(type)
    setTimeout(() => setCopied(null), 2000)
  }

  // Resolve readable text against the rendered swatch color, including alpha tokens.
  const getContrastColor = (hexColor: string): string => {
    const toLinear = (channel: number) => {
      const value = channel / 255
      return value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4
    }
    const luminance = ([r, g, b]: [number, number, number]) =>
      0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b)
    const contrast = (
      foreground: [number, number, number],
      background: [number, number, number],
    ) => {
      const lighter = Math.max(luminance(foreground), luminance(background))
      const darker = Math.min(luminance(foreground), luminance(background))
      return (lighter + 0.05) / (darker + 0.05)
    }
    const compositeOverWhite = ([r, g, b, a]: [number, number, number, number]) =>
      [
        Math.round(r * a + 255 * (1 - a)),
        Math.round(g * a + 255 * (1 - a)),
        Math.round(b * a + 255 * (1 - a)),
      ] as [number, number, number]

    const rgbaMatch = hexColor.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([0-9.]+))?\)$/i)
    const rgba = rgbaMatch
      ? ([
          Number(rgbaMatch[1]),
          Number(rgbaMatch[2]),
          Number(rgbaMatch[3]),
          Number(rgbaMatch[4] ?? 1),
        ] as [number, number, number, number])
      : undefined

    const value = hexColor.replace("#", "")
    const normalized =
      value.length === 3
        ? value
            .split("")
            .map((part) => `${part}${part}`)
            .join("")
        : value
    const hexRgba = /^[0-9a-f]{6}([0-9a-f]{2})?$/i.test(normalized)
      ? ([
          Number.parseInt(normalized.slice(0, 2), 16),
          Number.parseInt(normalized.slice(2, 4), 16),
          Number.parseInt(normalized.slice(4, 6), 16),
          normalized.length === 8 ? Number.parseInt(normalized.slice(6, 8), 16) / 255 : 1,
        ] as [number, number, number, number])
      : undefined

    const background = rgba ?? hexRgba
    if (!background) return "#141414"

    const renderedBackground = compositeOverWhite(background)
    const black: [number, number, number] = [0, 0, 0]
    const white: [number, number, number] = [255, 255, 255]

    return contrast(black, renderedBackground) >= contrast(white, renderedBackground)
      ? "#141414"
      : "#FFFFFF"
  }

  const textColor = getContrastColor(hex)

  return (
    <div className="color-swatch">
      <div className="color-swatch__preview" style={{ backgroundColor: hex }}>
        <Paragraph style={{ color: textColor }}>{hex}</Paragraph>
      </div>

      <div className="color-swatch__info">
        <Paragraph>{name}</Paragraph>

        <div className="color-swatch__values">
          <button
            type="button"
            className="color-swatch__value"
            onClick={() => copyToClipboard(hex, "hex")}
            title="Click to copy hex value"
          >
            <Paragraph size="sm" className="color-swatch__value-label">
              HEX:
            </Paragraph>
            <Paragraph size="sm" className="color-swatch__value-text">
              {hex}
            </Paragraph>
            {copied === "hex" && <span className="color-swatch__copied">✓</span>}
          </button>

          <button
            type="button"
            className="color-swatch__value"
            onClick={() => copyToClipboard(cssVar, "var")}
            title="Click to copy CSS variable"
          >
            <Paragraph size="sm">CSS:</Paragraph>
            <Paragraph size="sm">{cssVar}</Paragraph>
            {copied === "var" && <span className="color-swatch__copied">✓</span>}
          </button>
        </div>

        {description && <Paragraph size="sm">{description}</Paragraph>}

        {usage && (
          <Paragraph size="sm">
            <strong>Usage:</strong> {usage}
          </Paragraph>
        )}
      </div>
    </div>
  )
}

// apps/storybook-svelte/src/stories/color/ColorSwatch.svelte
<script lang="ts">
  import { Paragraph } from "@marwes-ui/svelte"

  interface Props {
    name: string
    hex: string
    cssVar: string
    description?: string
    usage?: string
  }

  let { name, hex, cssVar, description, usage }: Props = $props()

  let copied = $state<"hex" | "var" | null>(null)

  function getContrastColor(hexColor: string): string {
    const toLinear = (channel: number) => {
      const value = channel / 255
      return value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4
    }
    const luminance = ([r, g, b]: [number, number, number]) =>
      0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b)

    const raw = hexColor.replace("#", "")
    const normalized =
      raw.length === 3
        ? raw.split("").map((c) => `${c}${c}`).join("")
        : raw

    if (!/^[0-9a-f]{6}([0-9a-f]{2})?$/i.test(normalized)) return "#141414"

    const r = Number.parseInt(normalized.slice(0, 2), 16)
    const g = Number.parseInt(normalized.slice(2, 4), 16)
    const b = Number.parseInt(normalized.slice(4, 6), 16)
    const lum = luminance([r, g, b])

    return lum > 0.179 ? "#141414" : "#FFFFFF"
  }

  function copyToClipboard(text: string, type: "hex" | "var"): void {
    navigator.clipboard.writeText(text)
    copied = type
    setTimeout(() => { copied = null }, 2000)
  }

  const textColor = $derived(getContrastColor(hex))
</script>

<div class="color-swatch">
  <div class="color-swatch__preview" style="background-color: {hex};">
    <Paragraph style="color: {textColor};">{hex}</Paragraph>
  </div>

  <div class="color-swatch__info">
    <Paragraph>{name}</Paragraph>

    <div class="color-swatch__values">
      <button
        type="button"
        class="color-swatch__value"
        onclick={() => copyToClipboard(hex, "hex")}
        title="Click to copy hex value"
      >
        <Paragraph size="sm" class="color-swatch__value-label">HEX:</Paragraph>
        <Paragraph size="sm" class="color-swatch__value-text">{hex}</Paragraph>
        {#if copied === "hex"}
          <span class="color-swatch__copied" aria-hidden="true">✓</span>
        {/if}
      </button>

      <button
        type="button"
        class="color-swatch__value"
        onclick={() => copyToClipboard(cssVar, "var")}
        title="Click to copy CSS variable"
      >
        <Paragraph size="sm" class="color-swatch__value-label">CSS:</Paragraph>
        <Paragraph size="sm" class="color-swatch__value-text">{cssVar}</Paragraph>
        {#if copied === "var"}
          <span class="color-swatch__copied" aria-hidden="true">✓</span>
        {/if}
      </button>
    </div>

    {#if description}
      <Paragraph size="sm">{description}</Paragraph>
    {/if}

    {#if usage}
      <Paragraph size="sm"><strong>Usage:</strong> {usage}</Paragraph>
    {/if}
  </div>
</div>

<style>
  .color-swatch {
    display: flex;
    flex-direction: column;
    border: 1px solid #d8d8d8;
    border-radius: 8px;
    overflow: hidden;
    background: white;
    color: #141414;
    transition: box-shadow 0.2s;
  }
  .color-swatch:hover {
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  }
  .color-swatch__preview {
    height: 120px;
    display: flex;
    align-items: flex-end;
    justify-content: center;
    padding: 12px;
    font-weight: 500;
    font-size: 14px;
    font-family: "SF Mono", Monaco, "Cascadia Code", "Courier New", monospace;
  }
  .color-swatch__info {
    padding: 16px;
    display: flex;
    flex-direction: column;
    gap: 8px;
    color: #141414;
  }
  .color-swatch__values {
    display: flex;
    flex-direction: column;
    gap: 4px;
  }
  .color-swatch__value {
    display: flex;
    align-items: center;
    gap: 8px;
    padding: 6px 8px;
    background: #f9fafb;
    border: 1px solid #d8d8d8;
    border-radius: 4px;
    font-size: 13px;
    font-family: "SF Mono", Monaco, "Cascadia Code", "Courier New", monospace;
    cursor: pointer;
    transition: all 0.15s;
    text-align: left;
  }
  .color-swatch__value:hover {
    background: #f5f5f5;
    border-color: #a3a3a3;
  }
  .color-swatch__value:active {
    background: #d8d8d8;
  }
  .color-swatch__copied {
    color: #006633;
    font-weight: 700;
    animation: fadeIn 0.2s;
  }
  @keyframes fadeIn {
    from { opacity: 0; transform: scale(0.8); }
    to { opacity: 1; transform: scale(1); }
  }
</style>
