// packages/svelte/src/lib/components/toast/ToastContainer.svelte
<script lang="ts">
  import { mergeClass } from "../../internal/merge-class.js";
  import ErrorToast from "./ErrorToast.svelte";
  import InfoToast from "./InfoToast.svelte";
  import SuccessToast from "./SuccessToast.svelte";
  import Toast from "./Toast.svelte";
  import WarningToast from "./WarningToast.svelte";
  import type { ManagedToast, ToastContainerProps } from "./types.js";

  let {
    toasts,
    placement = "top-right",
    maxVisible,
    class: className,
    ondismiss,
  }: ToastContainerProps = $props();

  const mergedClass = $derived(
    mergeClass("mw-toast-container", `mw-toast-container--${placement}`, className)
  );

  const visibleToasts = $derived(
    maxVisible && maxVisible > 0 ? toasts.slice(-maxVisible) : toasts
  );
</script>

<div class={mergedClass}>
  {#each visibleToasts as toast (toast.id)}
    <div class="mw-toast-container__item">
      {#if toast.intent === "success"}
        <SuccessToast
          id={toast.id}
          {...(toast.class ? { class: toast.class } : {})}
          {...(toast.variant ? { variant: toast.variant } : {})}
          {...(toast.ariaLive ? { ariaLive: toast.ariaLive } : {})}
          {...(ondismiss ? { ondismiss: () => ondismiss(toast.id) } : {})}
          {...(toast.dataAttributes ? { dataAttributes: toast.dataAttributes } : {})}
        >
          {#snippet children()}{toast.message}{/snippet}
        </SuccessToast>
      {:else if toast.intent === "error"}
        <ErrorToast
          id={toast.id}
          {...(toast.class ? { class: toast.class } : {})}
          {...(toast.variant ? { variant: toast.variant } : {})}
          {...(toast.ariaLive ? { ariaLive: toast.ariaLive } : {})}
          {...(ondismiss ? { ondismiss: () => ondismiss(toast.id) } : {})}
          {...(toast.dataAttributes ? { dataAttributes: toast.dataAttributes } : {})}
        >
          {#snippet children()}{toast.message}{/snippet}
        </ErrorToast>
      {:else if toast.intent === "warning"}
        <WarningToast
          id={toast.id}
          {...(toast.class ? { class: toast.class } : {})}
          {...(toast.variant ? { variant: toast.variant } : {})}
          {...(toast.ariaLive ? { ariaLive: toast.ariaLive } : {})}
          {...(ondismiss ? { ondismiss: () => ondismiss(toast.id) } : {})}
          {...(toast.dataAttributes ? { dataAttributes: toast.dataAttributes } : {})}
        >
          {#snippet children()}{toast.message}{/snippet}
        </WarningToast>
      {:else if toast.intent === "info"}
        <InfoToast
          id={toast.id}
          {...(toast.class ? { class: toast.class } : {})}
          {...(toast.variant ? { variant: toast.variant } : {})}
          {...(toast.ariaLive ? { ariaLive: toast.ariaLive } : {})}
          {...(ondismiss ? { ondismiss: () => ondismiss(toast.id) } : {})}
          {...(toast.dataAttributes ? { dataAttributes: toast.dataAttributes } : {})}
        >
          {#snippet children()}{toast.message}{/snippet}
        </InfoToast>
      {:else}
        <Toast
          id={toast.id}
          {...(toast.class ? { class: toast.class } : {})}
          {...(toast.variant ? { variant: toast.variant } : {})}
          {...(toast.ariaLive ? { ariaLive: toast.ariaLive } : {})}
          {...(ondismiss ? { ondismiss: () => ondismiss(toast.id) } : {})}
          {...(toast.dataAttributes ? {
            dataAttributes: {
              ...toast.dataAttributes,
              ...(toast.intent ? { "data-intent": toast.intent } : {}),
            },
          } : (toast.intent ? { dataAttributes: { "data-intent": toast.intent } } : {}))}
        >
          {#snippet children()}{toast.message}{/snippet}
        </Toast>
      {/if}
    </div>
  {/each}
</div>

// packages/react/src/components/toast/toast-container.tsx
import type { ToastIntent } from "@marwes-ui/core"
import * as React from "react"
import { Toast, type ToastProps } from "./toast"
import type { ManagedToast, ToastContainerProps } from "./toast-manager-types"
import { ErrorToast, InfoToast, SuccessToast, WarningToast } from "./variants"

function cx(...parts: Array<string | false | undefined>): string {
  return parts.filter(Boolean).join(" ")
}

function renderToastByIntent(
  toast: ManagedToast,
  onDismiss: ((id: string) => void) | undefined,
): React.ReactElement {
  const sharedProps: ToastProps = {
    id: toast.id,
    children: toast.children,
  }
  const dismissHandler = onDismiss ? () => onDismiss(toast.id) : undefined

  if (toast.icon !== undefined) {
    sharedProps.icon = toast.icon
  }

  if (toast.action !== undefined) {
    sharedProps.action = toast.action
  }

  if (dismissHandler) {
    sharedProps.onDismiss = dismissHandler
  }

  if (toast.className !== undefined) {
    sharedProps.className = toast.className
  }

  if (toast.variant !== undefined) {
    sharedProps.variant = toast.variant
  }

  if (toast.ariaLive !== undefined) {
    sharedProps.ariaLive = toast.ariaLive
  }

  if (toast.dataAttributes !== undefined || toast.intent !== undefined) {
    sharedProps.dataAttributes = {
      ...(toast.dataAttributes ?? {}),
      ...(toast.intent !== undefined ? { "data-intent": toast.intent } : {}),
    }
  }

  switch (toast.intent as ToastIntent | undefined) {
    case "success":
      return <SuccessToast {...sharedProps} />
    case "error":
      return <ErrorToast {...sharedProps} />
    case "warning":
      return <WarningToast {...sharedProps} />
    case "info":
      return <InfoToast {...sharedProps} />
    default:
      return <Toast {...sharedProps} />
  }
}

function ToastViewportItem(props: {
  toast: ManagedToast
  onDismiss?: (id: string) => void
}): React.ReactElement {
  React.useEffect(() => {
    if (!props.onDismiss || props.toast.duration === undefined || props.toast.duration === null) {
      return
    }

    if (props.toast.duration <= 0) {
      return
    }

    const timer = window.setTimeout(() => {
      props.onDismiss?.(props.toast.id)
    }, props.toast.duration)

    return () => {
      window.clearTimeout(timer)
    }
  }, [props.onDismiss, props.toast.duration, props.toast.id])

  return (
    <div className="mw-toast-container__item">
      {renderToastByIntent(props.toast, props.onDismiss)}
    </div>
  )
}

export function ToastContainer(props: ToastContainerProps): React.ReactElement {
  const placement = props.placement ?? "top-right"
  const visibleToasts =
    props.maxVisible && props.maxVisible > 0 ? props.toasts.slice(-props.maxVisible) : props.toasts

  return (
    <div className={cx("mw-toast-container", `mw-toast-container--${placement}`, props.className)}>
      {visibleToasts.map((toast) => (
        <ToastViewportItem
          key={toast.id}
          toast={toast}
          {...(props.onDismiss ? { onDismiss: props.onDismiss } : {})}
        />
      ))}
    </div>
  )
}
