// packages/svelte/src/lib/components/toast/ToastProvider.svelte
<script lang="ts" module>
  import { getContext, setContext } from "svelte";
  import type { ToastController } from "./types.js";

  const TOAST_CONTEXT_KEY = Symbol("marwes-toast");

  export function setToastContext(controller: ToastController): void {
    setContext(TOAST_CONTEXT_KEY, controller);
  }

  export function useToast(): ToastController {
    const ctx = getContext<ToastController | undefined>(TOAST_CONTEXT_KEY);
    if (!ctx) {
      throw new Error("ToastProvider is missing. Wrap your app in <ToastProvider />.");
    }
    return ctx;
  }
</script>

<script lang="ts">
  import ToastContainer from "./ToastContainer.svelte";
  import type { ManagedToast, ShowToastOptions, ToastProviderProps } from "./types.js";

  let {
    children,
    placement,
    maxVisible,
    defaultDuration,
    class: className,
  }: ToastProviderProps = $props();

  let toasts = $state<ManagedToast[]>([]);
  let nextId = $state(0);

  function show(options: ShowToastOptions): string {
    nextId += 1;
    const id = `mw-toast-${nextId}`;
    const duration = options.duration === undefined
      ? (defaultDuration === undefined ? 4000 : defaultDuration)
      : options.duration;

    toasts = [...toasts, { ...options, id, duration }];

    return id;
  }

  function dismiss(id: string): void {
    const toast = toasts.find((t) => t.id === id);
    toast?.ondismiss?.();
    toasts = toasts.filter((t) => t.id !== id);
  }

  function clear(): void {
    for (const toast of toasts) {
      toast.ondismiss?.();
    }
    toasts = [];
  }

  const controller: ToastController = { show, dismiss, clear };
  setToastContext(controller);
</script>

{@render children?.()}
<ToastContainer
  {toasts}
  ondismiss={dismiss}
  {...(placement ? { placement } : {})}
  {...(maxVisible !== undefined ? { maxVisible } : {})}
  {...(className ? { class: className } : {})}
/>

// packages/react/src/components/toast/toast-provider.tsx
import * as React from "react"
import { ToastContainer } from "./toast-container"
import type {
  ManagedToast,
  ShowToastOptions,
  ToastController,
  ToastProviderProps,
} from "./toast-manager-types"

const ToastContext = React.createContext<ToastController | null>(null)

export function ToastProvider(props: ToastProviderProps): React.ReactElement {
  const [toasts, setToasts] = React.useState<ManagedToast[]>([])
  const idRef = React.useRef(0)

  const dismiss = React.useCallback((id: string) => {
    setToasts((currentToasts) => {
      const toast = currentToasts.find((item) => item.id === id)
      toast?.onDismiss?.()
      return currentToasts.filter((item) => item.id !== id)
    })
  }, [])

  const clear = React.useCallback(() => {
    setToasts((currentToasts) => {
      for (const toast of currentToasts) {
        toast.onDismiss?.()
      }

      return []
    })
  }, [])

  const show = React.useCallback(
    (toast: ShowToastOptions) => {
      idRef.current += 1
      const id = `mw-toast-${idRef.current}`

      setToasts((currentToasts) => [
        ...currentToasts,
        {
          ...toast,
          id,
          duration:
            toast.duration === undefined
              ? props.defaultDuration === undefined
                ? 4000
                : props.defaultDuration
              : toast.duration,
        },
      ])

      return id
    },
    [props.defaultDuration],
  )

  const value = React.useMemo<ToastController>(
    () => ({
      show,
      dismiss,
      clear,
    }),
    [clear, dismiss, show],
  )

  return (
    <ToastContext.Provider value={value}>
      {props.children}
      <ToastContainer
        toasts={toasts}
        onDismiss={dismiss}
        {...(props.placement ? { placement: props.placement } : {})}
        {...(props.maxVisible !== undefined ? { maxVisible: props.maxVisible } : {})}
        {...(props.className ? { className: props.className } : {})}
      />
    </ToastContext.Provider>
  )
}

export function useToast(): ToastController {
  const context = React.useContext(ToastContext)

  if (!context) {
    throw new Error("ToastProvider is missing. Wrap your app in <ToastProvider />.")
  }

  return context
}
