// packages/react/src/components/stat-tile/stat-tile.tsx
import {
  type StatTileOptions,
  type StatTileTone,
  type StatTileTrendDirection,
  createStatTileRecipe,
  toStatTileTrendHtmlAttributes,
} from "@marwes-ui/core"
import type * as React from "react"
import { toReactAttributes } from "../../internal/react-attributes"

export interface StatTileProps
  extends Omit<React.HTMLAttributes<HTMLElement>, "children" | "title">,
    Pick<StatTileOptions, "dataAttributes"> {
  label: React.ReactNode
  value: React.ReactNode
  subtitle?: React.ReactNode
  trendValue?: React.ReactNode
  trendDirection?: StatTileTrendDirection
  tone?: StatTileTone
}

export function StatTile(props: StatTileProps): React.ReactElement {
  const {
    className,
    dataAttributes,
    label,
    value,
    subtitle,
    trendValue,
    trendDirection,
    tone,
    ...nativeArticleProps
  } = props
  const kit = createStatTileRecipe({
    ...(tone !== undefined ? { tone } : {}),
    ...(trendDirection !== undefined ? { trendDirection } : {}),
    ...(typeof trendValue === "string" ? { trendValue } : {}),
    ...(dataAttributes !== undefined ? { dataAttributes } : {}),
  })
  const mergedClassName = [kit.className, className].filter(Boolean).join(" ")

  return (
    <article {...nativeArticleProps} {...kit.dataAttributes} className={mergedClassName}>
      <div className={kit.slots.headerClassName}>
        <span className={kit.slots.labelClassName}>{label}</span>
        {trendValue ? (
          <span
            {...kit.trendDataAttributes}
            className={kit.slots.trendClassName}
            {...toReactAttributes(toStatTileTrendHtmlAttributes(kit.a11y))}
          >
            {kit.trendIcon ? (
              <span className={kit.slots.trendIconClassName} aria-hidden="true">
                {kit.trendIcon}
              </span>
            ) : null}
            <span className={kit.slots.trendValueClassName}>{trendValue}</span>
          </span>
        ) : null}
      </div>
      <div className={kit.slots.valueClassName}>{value}</div>
      {subtitle ? <div className={kit.slots.subtitleClassName}>{subtitle}</div> : null}
    </article>
  )
}

// packages/svelte/src/lib/components/stat-tile/StatTile.svelte
<script lang="ts">
  import { createStatTileRecipe, toStatTileTrendHtmlAttributes } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { StatTileProps } from "./types.js";

  let {
    label,
    value,
    subtitle,
    trendValue,
    dataAttributes,
    class: className,
    ...options
  }: StatTileProps = $props();

  const kit = $derived(createStatTileRecipe({
    ...options,
    ...(trendValue ? { trendValue } : {}),
    ...(dataAttributes ? { dataAttributes } : {}),
  }));
  const mergedClass = $derived(mergeClass(kit.className, className));
</script>

<article class={mergedClass} {...kit.dataAttributes}>
  <div class={kit.slots.headerClassName}>
    <span class={kit.slots.labelClassName}>{label}</span>
    {#if trendValue}
      <span
        class={kit.slots.trendClassName}
        {...toStatTileTrendHtmlAttributes(kit.a11y)}
        {...kit.trendDataAttributes}
      >
        {#if kit.trendIcon}
          <span class={kit.slots.trendIconClassName} aria-hidden="true">{kit.trendIcon}</span>
        {/if}
        <span class={kit.slots.trendValueClassName}>{trendValue}</span>
      </span>
    {/if}
  </div>
  <div class={kit.slots.valueClassName}>{value}</div>
  {#if subtitle}
    <div class={kit.slots.subtitleClassName}>{subtitle}</div>
  {/if}
</article>
