// packages/react/src/components/badge/badge.tsx
import { createBadgeRecipe } from "@marwes-ui/core"
import type { BadgeOptions } from "@marwes-ui/core"
import type * as React from "react"

export type BadgeProps = BadgeOptions & {
  children?: React.ReactNode
  className?: string
  id?: string
}

export function Badge(props: BadgeProps): React.ReactElement {
  const { children, className, id, ...coreProps } = props
  const kit = createBadgeRecipe(coreProps)

  return (
    <span
      id={id}
      className={[kit.className, className].filter(Boolean).join(" ")}
      aria-label={kit.a11y.ariaLabel}
    >
      {children}
    </span>
  )
}

// packages/svelte/src/lib/components/badge/Badge.svelte
<script lang="ts">
  import { createBadgeRecipe } from "@marwes-ui/core";
  import { mergeClass } from "../../internal/merge-class.js";
  import type { BadgeProps } from "./types.js";

  let {
    children,
    class: className,
    id,
    dataAttributes,
    ...coreProps
  }: BadgeProps = $props();

  const kit = $derived(createBadgeRecipe(coreProps));
  const mergedClass = $derived(mergeClass(kit.className, className));
</script>

<span
  {id}
  class={mergedClass}
  aria-label={kit.a11y.ariaLabel}
  {...kit.dataAttributes}
  {...dataAttributes}
>
  {@render children?.()}
</span>
